import type { Scene } from '../../../engine/types'

/** Escenas de la misión 0 del curso 2 (Equipo nuevo). */
export const m00Scenes: Scene[] = [
  {
    id: 'mail_raul',
    channel: 'email',
    from: 'raul',
    at: 0,
    subject: 'Bienvenida al squad Empresas',
    body: '¡Bienvenida al squad! 🎉\n\nAquí cada uno prueba a su manera y nadie sabe qué está probado. Necesito una propuesta de proceso de pruebas para el comité de hoy a las 15:00: qué actividades hacemos, qué sale de cada una y quién se encarga.\n\nRaúl',
  },
  {
    id: 'mail_carmen',
    channel: 'email',
    from: 'carmen',
    at: 0,
    subject: 'Auditoría de Tarjetas de equipo',
    body: 'Hola. A las 14:00 tengo una llamada con auditoría y me van a preguntar qué historias de «Tarjetas de equipo» tienen defectos abiertos y si cada requisito está probado. ¿Me preparas la matriz de trazabilidad? Está a medias en la app «Proceso».\n\nCarmen · Riesgos y Compliance',
  },
  {
    id: 'daily',
    channel: 'meeting',
    from: 'raul',
    with: ['tomas', 'sofia', 'elena'],
    at: 15,
    subject: '09:15 · Daily · Squad Empresas',
    body: '**Tomás:** Propongo algo sencillo: cada dev prueba su propio código y nos ahorramos un QA en medio. Somos mayores.\n\n**Raúl:** ¿Qué opinas tú, que acabas de llegar?',
    choices: [
      {
        id: 'whole',
        text: 'La calidad es de todo el equipo: los devs probáis vuestro código (unitarias, TDD) y yo os ayudo. Pero además hace falta una mirada independiente a nivel de sistema: quien escribe el código tiene los mismos sesgos al probarlo.',
        cost: 10,
        reply: 'Vale, tiene sentido: no es «o devs o QA», es los dos.',
        replyFrom: 'tomas',
        effects: [
          { kind: 'flag', key: 'team.indep' },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'unlock', conceptId: 'whole_team' },
          { kind: 'unlock', conceptId: 'independence' },
          { kind: 'note', tone: 'good', text: 'Defendiste el enfoque de equipo completo sin renunciar a la independencia de las pruebas.' },
        ],
      },
      {
        id: 'devs',
        text: 'Tienes razón, si cada uno prueba lo suyo es suficiente.',
        cost: 5,
        reply: '¡Perfecto, menos reuniones!',
        replyFrom: 'tomas',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'independence' },
          { kind: 'note', tone: 'bad', text: 'Aceptaste que solo el autor pruebe su código: sin independencia, los mismos sesgos que crearon el defecto lo esconden.' },
        ],
      },
      {
        id: 'qa_only',
        text: 'No: las pruebas son cosa de QA. Los devs, a programar.',
        cost: 5,
        reply: 'Pues vaya… yo quería aprender a escribir tests 😕',
        replyFrom: 'sofia',
        effects: [
          { kind: 'score', key: 'communication', add: -1 },
          { kind: 'unlock', conceptId: 'whole_team' },
          { kind: 'note', tone: 'bad', text: 'Sacaste a desarrollo de las pruebas: la calidad es responsabilidad de todo el equipo.' },
        ],
      },
    ],
  },
  {
    id: 'laura_hello',
    channel: 'chat',
    from: 'laura',
    at: 45,
    body: '¡Hola! Para la propuesta de Raúl te servirá la guía del proceso de pruebas de la wiki. Y no te olvides de la matriz de Carmen: a las 14:00 la necesita.',
    onDeliver: [{ kind: 'unlock', conceptId: 'test_activities' }],
  },
  {
    id: 'tomas_closure',
    channel: 'meeting',
    from: 'tomas',
    with: ['sofia'],
    at: 150,
    subject: '11:30 · Café con Tomás y Sofía',
    body: '**Tomás:** Oye, he oído que en tu proceso va a haber «cierre de pruebas» con lecciones aprendidas. ¿No es papeleo? Terminamos el sprint y a por el siguiente.',
    choices: [
      {
        id: 'keep',
        text: 'Es corto: archivar el testware útil, ver qué falló y apuntar qué cambiamos. Si no, en el siguiente sprint repetimos los mismos errores.',
        cost: 5,
        reply: 'Si son 30 minutos y sirve para no tropezar dos veces, me vale.',
        replyFrom: 'tomas',
        effects: [
          { kind: 'score', key: 'rigor', add: 1 },
          { kind: 'unlock', conceptId: 'test_activities' },
          { kind: 'note', tone: 'good', text: 'Mantuviste el cierre de pruebas: sin él, el equipo no aprende de un sprint a otro.' },
        ],
      },
      {
        id: 'drop',
        text: 'Vale, lo quito; total, nadie lo lee.',
        cost: 5,
        reply: '👍',
        replyFrom: 'tomas',
        effects: [
          { kind: 'flag', key: 'proc.drop_closure' },
          { kind: 'unlock', conceptId: 'test_activities' },
          { kind: 'note', tone: 'bad', text: 'Quitaste el cierre de pruebas del proceso.' },
        ],
      },
    ],
  },
  {
    id: 'laura_proposal_ok',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'proc.all' },
    body: 'He visto tu propuesta: actividades en orden, cada una con su testware y su responsable. Muy limpio 👌',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: 1 },
      { kind: 'unlock', conceptId: 'testware' },
      { kind: 'unlock', conceptId: 'test_roles' },
      { kind: 'note', tone: 'good', text: 'Propusiste un proceso coherente: actividades, testware y roles.' },
    ],
  },
  {
    id: 'laura_proposal_gaps',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'all', of: [{ kind: 'flag', key: 'proc.submitted' }, { kind: 'notFlag', key: 'proc.all' }] },
    body: 'He visto tu propuesta. Hay cosas por pulir: revisa el orden, qué produce cada actividad o quién la lleva. Mira el debrief al final del día.',
    onDeliver: [
      { kind: 'unlock', conceptId: 'testware' },
      { kind: 'unlock', conceptId: 'test_roles' },
      { kind: 'note', tone: 'bad', text: 'La propuesta de proceso tenía actividades fuera de orden, testware mal asignado o roles cambiados.' },
    ],
  },
  {
    id: 'carmen_call',
    channel: 'meeting',
    from: 'carmen',
    at: 300,
    subject: '14:00 · Carmen: llamada con auditoría',
    body: '**Carmen:** Estoy con auditoría. ¿Qué historias de Tarjetas de equipo tienen defectos abiertos? ¿Y cómo lo sabes?',
    onDeliver: [{ kind: 'unlock', conceptId: 'traceability' }],
    choices: [
      {
        id: 'trace',
        text: 'H1 (límite de gasto) y H2 (bloqueo). D1 lo detectó T5, que prueba C1, de H1; D2 lo detectó T3, que prueba C3, de H2. H3 tiene su condición probada y sin defectos.',
        requires: { kind: 'flag', key: 'trace.ok' },
        cost: 10,
        reply: 'Perfecto, y con la cadena completa. Auditoría satisfecha.',
        replyFrom: 'carmen',
        effects: [
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'note', tone: 'good', text: 'Respondiste a auditoría con la trazabilidad completa de historias a defectos.' },
        ],
      },
      {
        id: 'guess',
        text: 'Creo que la de límites y alguna más… no lo tengo enlazado del todo.',
        cost: 10,
        reply: 'Con «creo» no puedo ir a auditoría. Necesito saberlo.',
        replyFrom: 'carmen',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'note', tone: 'bad', text: 'No pudiste demostrar qué requisitos tenían defectos: faltaba trazabilidad.' },
        ],
      },
    ],
  },
  {
    id: 'committee',
    channel: 'meeting',
    from: 'raul',
    with: ['laura', 'elena', 'tomas'],
    at: 360,
    subject: '15:00 · Comité: proceso de pruebas del squad',
    body: '**Raúl:** Veamos la propuesta. Y una pregunta: ¿en qué momento entra QA en cada historia?',
    onDeliver: [
      {
        kind: 'if',
        when: { kind: 'all', of: [{ kind: 'flag', key: 'proc.submitted' }, { kind: 'notFlag', key: 'proc.drop_closure' }] },
        then: [{ kind: 'flag', key: 'proc.closure' }],
      },
      {
        kind: 'if',
        when: { kind: 'flag', key: 'proc.submitted' },
        then: [{ kind: 'score', key: 'efficiency', add: 2 }],
        else: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'note', tone: 'bad', text: 'Llegaste al comité sin propuesta de proceso.' },
        ],
      },
      { kind: 'if', when: { kind: 'flag', key: 'trace.ok' }, then: [{ kind: 'score', key: 'rigor', add: 1 }, { kind: 'score', key: 'efficiency', add: 1 }] },
      { kind: 'preventBugs' },
    ],
    choices: [
      {
        id: 'early',
        text: 'Desde el refinamiento: cada actividad de desarrollo tiene su actividad de pruebas, el análisis y el diseño empiezan en cuanto hay historia, y reviso los borradores. Cuanto antes, más barato es el defecto.',
        cost: 15,
        reply: 'Me convence. Aprobado como proceso del squad.',
        replyFrom: 'raul',
        effects: [
          { kind: 'flag', key: 'sdlc.early' },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'unlock', conceptId: 'sdlc_testing' },
          { kind: 'note', tone: 'good', text: 'Situaste las pruebas desde el principio del ciclo de vida (shift-left).' },
        ],
      },
      {
        id: 'late',
        text: 'Cuando desarrollo termina la historia, para no molestar.',
        cost: 10,
        reply: 'Hmm… entonces los defectos de la historia los vamos a ver muy tarde.',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'sdlc_testing' },
          { kind: 'note', tone: 'bad', text: 'Dejaste las pruebas para después del desarrollo: los defectos se encuentran tarde y caros.' },
        ],
      },
    ],
  },
  {
    id: 'closing',
    channel: 'meeting',
    from: 'laura',
    at: 480,
    subject: '17:00 · Café con Laura',
    body: '**Laura:** Primer día de responsable de calidad del squad. ¿Qué te llevas?',
    choices: [
      {
        id: 'lesson',
        text: 'Que un proceso de pruebas no es «probar al final»: son actividades con su testware y sus responsables, trazables de la historia al defecto, con todo el equipo implicado y una mirada independiente.',
        reply: 'Exacto. Y mañana empezamos a usarlo de verdad.',
        effects: [{ kind: 'score', key: 'communication', add: 1 }, { kind: 'endMission' }],
      },
      {
        id: 'waste',
        text: 'Que hay demasiada burocracia para probar.',
        reply: 'Mira en el debrief qué pasa cuando falta cada pieza.',
        effects: [{ kind: 'note', tone: 'neutral', text: 'Te quedaste con el coste del proceso, no con lo que evita.' }, { kind: 'endMission' }],
      },
    ],
  },
]
