import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulos 1.4, 1.5 y 2.1). */
export const m00Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m0pre_analysis',
      conceptId: 'test_activities',
      question: '¿En qué actividad se decide QUÉ probar, identificando condiciones de prueba? (K1)',
      options: ['Planificación', 'Análisis', 'Diseño', 'Implementación'],
      correct: 1,
      explanation: 'El análisis responde a «qué probar»; el diseño, a «cómo probarlo».',
    },
    {
      id: 'c2m0pre_testware',
      conceptId: 'testware',
      question: '¿Qué testware es resultado típico de la implementación de pruebas? (K2)',
      options: ['El plan de pruebas', 'Los procedimientos y los datos de prueba', 'El informe de cierre', 'Las condiciones de prueba'],
      correct: 1,
      explanation: 'En la implementación se preparan procedimientos, datos, scripts y entorno.',
    },
    {
      id: 'c2m0pre_trace',
      conceptId: 'traceability',
      question: '¿Cuál es un beneficio de la trazabilidad entre base de prueba y casos de prueba? (K2)',
      options: ['Reduce el número de casos necesarios', 'Permite evaluar la cobertura y el impacto de los cambios', 'Sustituye a los informes de defectos', 'Garantiza que no haya defectos'],
      correct: 1,
      explanation: 'La trazabilidad permite medir la cobertura y analizar el impacto de los cambios.',
    },
    {
      id: 'c2m0pre_roles',
      conceptId: 'test_roles',
      question: '¿En qué actividades se centra principalmente el rol de gestión de pruebas? (K1)',
      options: ['Análisis y diseño', 'Implementación y ejecución', 'Planificación, seguimiento y control, y cierre', 'Solo la ejecución'],
      correct: 2,
      explanation: 'La gestión de pruebas se centra en planificación, seguimiento y control, y cierre.',
    },
    {
      id: 'c2m0pre_indep',
      conceptId: 'independence',
      question: '¿Por qué un probador independiente suele encontrar defectos que el autor no ve? (K2)',
      options: ['Porque tiene más tiempo', 'Porque tiene sesgos cognitivos distintos de los del autor', 'Porque usa mejores herramientas', 'Porque conoce mejor el código'],
      correct: 1,
      explanation: 'El autor comparte los sesgos que causaron el defecto; otra persona no.',
    },
    {
      id: 'c2m0pre_sdlc',
      conceptId: 'sdlc_testing',
      question: '¿Cuál es una buena práctica de pruebas en cualquier ciclo de vida? (K1)',
      options: ['Empezar a probar cuando el código está terminado', 'Que cada actividad de desarrollo tenga su actividad de pruebas correspondiente', 'Probar solo en producción', 'Que solo QA revise los requisitos al final'],
      correct: 1,
      explanation: 'Cada actividad de desarrollo tiene su actividad de pruebas, y el análisis y el diseño empiezan pronto.',
    },
  ],
  post: [
    {
      id: 'c2m0post_closure',
      conceptId: 'test_activities',
      question: 'Un equipo repite en cada sprint los mismos problemas de entorno. ¿Qué actividad se están saltando? (K2)',
      options: ['Análisis', 'Diseño', 'Cierre de pruebas', 'Implementación'],
      correct: 2,
      explanation: 'En el cierre se evalúa y se registran las lecciones aprendidas.',
    },
    {
      id: 'c2m0post_testware',
      conceptId: 'testware',
      question: '¿Qué actividad produce las condiciones de prueba priorizadas? (K1)',
      options: ['Planificación', 'Análisis', 'Ejecución', 'Cierre'],
      correct: 1,
      explanation: 'El análisis produce las condiciones de prueba priorizadas.',
    },
    {
      id: 'c2m0post_trace',
      conceptId: 'traceability',
      question: 'Auditoría pregunta qué requisitos tienen defectos abiertos. ¿Qué lo permite responder? (K2)',
      options: ['El plan de pruebas', 'La trazabilidad de defectos a casos, condiciones y requisitos', 'Las métricas de rendimiento', 'El número de casos ejecutados'],
      correct: 1,
      explanation: 'Con la cadena requisito → condición → caso → defecto se sabe qué requisitos afecta cada defecto.',
    },
    {
      id: 'c2m0post_roles',
      conceptId: 'test_roles',
      question: '¿Qué afirmación sobre los roles de prueba es correcta? (K2)',
      options: ['Son puestos fijos que no se pueden combinar', 'Una misma persona puede asumir los roles de gestión y de tester según el contexto', 'El tester se ocupa de la planificación', 'La gestión de pruebas ejecuta todos los casos'],
      correct: 1,
      explanation: 'Son roles, no puestos; quién los asume depende del contexto.',
    },
    {
      id: 'c2m0post_whole',
      conceptId: 'whole_team',
      question: 'En el enfoque de equipo completo, ¿quién es responsable de la calidad? (K1)',
      options: ['Solo QA', 'Solo el Product Owner', 'Todo el equipo', 'El manager'],
      correct: 2,
      explanation: 'La calidad es responsabilidad de todo el equipo.',
    },
    {
      id: 'c2m0post_shift',
      conceptId: 'sdlc_testing',
      question: '¿Cuándo debería empezar el análisis de pruebas de una historia? (K2)',
      options: ['Cuando el código esté desplegado en pruebas', 'En cuanto exista la base de prueba (la historia), durante el refinamiento', 'Después de la demo', 'Solo si hay tiempo'],
      correct: 1,
      explanation: 'El análisis y el diseño empiezan en cuanto hay base de prueba: testing temprano.',
    },
  ],
}
