import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulo 3). */
export const m01Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m1pre_static',
      conceptId: 'static_testing',
      question: '¿Cuál es una ventaja del testing estático frente al dinámico? (K2)',
      options: ['Encuentra fallos de rendimiento en producción', 'Puede detectar defectos en productos de trabajo antes de que exista código ejecutable', 'Sustituye a las pruebas de sistema', 'Solo lo pueden hacer los testers'],
      correct: 1,
      explanation: 'El testing estático examina productos de trabajo sin ejecutarlos, así que se puede aplicar muy pronto.',
    },
    {
      id: 'c2m1pre_type',
      conceptId: 'review_types',
      question: 'Se necesita encontrar el máximo de defectos en un documento regulatorio y dejar evidencia para auditoría. ¿Qué tipo de revisión? (K2)',
      options: ['Revisión informal', 'Walkthrough', 'Inspección', 'Ninguna: basta con probar después'],
      correct: 2,
      explanation: 'La inspección es la más formal: preparación, roles, registro de defectos y métricas.',
    },
    {
      id: 'c2m1pre_moderator',
      conceptId: 'review_roles',
      question: '¿Qué rol se encarga de que la reunión de revisión sea eficaz y un entorno seguro? (K1)',
      options: ['Autor/a', 'Moderación (facilitador/a)', 'Escriba', 'Dirección'],
      correct: 1,
      explanation: 'La persona que modera dirige la reunión y media entre puntos de vista.',
    },
    {
      id: 'c2m1pre_steps',
      conceptId: 'review_process',
      question: '¿En qué actividad del proceso de revisión cada revisor/a examina el documento por su cuenta? (K1)',
      options: ['Planificación', 'Revisión individual', 'Comunicación y análisis', 'Corrección e informe'],
      correct: 1,
      explanation: 'En la revisión individual (preparación) cada revisor/a anota sus hallazgos.',
    },
    {
      id: 'c2m1pre_manager',
      conceptId: 'review_success',
      question: '¿Por qué suele ser mala idea que la dirección participe como revisora en la reunión? (K2)',
      options: ['Porque no sabe leer especificaciones', 'Porque los participantes tienden a callarse defectos delante de quien los evalúa', 'Porque alarga la reunión', 'Porque está prohibido por ISTQB'],
      correct: 1,
      explanation: 'La presión jerárquica reduce la apertura; la dirección apoya con recursos, no en la sala.',
    },
    {
      id: 'c2m1pre_defect',
      conceptId: 'static_testing',
      question: 'El testing estático encuentra principalmente… (K2)',
      options: ['Fallos', 'Defectos', 'Incidentes', 'Errores humanos'],
      correct: 1,
      explanation: 'Encuentra defectos directamente; los fallos aparecen al ejecutar.',
    },
  ],
  post: [
    {
      id: 'c2m1post_walk',
      conceptId: 'review_types',
      question: 'La autora quiere explicar un diseño nuevo al equipo, recoger ideas y crear consenso. ¿Qué tipo de revisión encaja mejor? (K2)',
      options: ['Inspección', 'Walkthrough', 'Revisión técnica', 'Auditoría'],
      correct: 1,
      explanation: 'El walkthrough lo guía la autora y sirve para formar, generar ideas y consenso.',
    },
    {
      id: 'c2m1post_scribe',
      conceptId: 'review_roles',
      question: '¿Quién recoge los defectos y decisiones durante la reunión? (K1)',
      options: ['Moderación', 'Escriba', 'Autor/a', 'Líder de la revisión'],
      correct: 1,
      explanation: 'La persona escriba (registrador/a) documenta defectos y decisiones.',
    },
    {
      id: 'c2m1post_followup',
      conceptId: 'review_process',
      question: 'Tras la reunión, la autora corrige el documento. ¿Qué falta para cerrar la revisión? (K2)',
      options: ['Nada', 'Comprobar que cada defecto registrado está corregido y comunicar el resultado', 'Volver a planificar la revisión', 'Borrar el acta'],
      correct: 1,
      explanation: 'Corrección e informe: se verifica cada corrección y se informa con evidencia.',
    },
    {
      id: 'c2m1post_feedback',
      conceptId: 'review_success',
      question: 'La autora se pone a la defensiva en la reunión. ¿Qué práctica ayuda? (K2)',
      options: ['Señalar quién cometió cada error', 'Centrarse en el producto de trabajo, no en la persona', 'Terminar la reunión', 'No registrar los defectos'],
      correct: 1,
      explanation: 'Un factor de éxito es dar feedback objetivo sobre el producto en un entorno seguro.',
    },
    {
      id: 'c2m1post_cost',
      conceptId: 'static_testing',
      question: '¿Por qué conviene encontrar defectos en una especificación antes del desarrollo? (K2)',
      options: ['Porque los testers tienen más tiempo', 'Porque corregirlos es más barato que cuando ya están en el código o en producción', 'Porque así no hacen falta pruebas dinámicas', 'Porque lo exige el cliente'],
      correct: 1,
      explanation: 'El coste de corregir un defecto crece cuanto más tarde se encuentra.',
    },
    {
      id: 'c2m1post_checklist',
      conceptId: 'review_process',
      question: '¿Qué aporta una checklist en la revisión individual? (K2)',
      options: ['Sustituye la reunión', 'Dirige la atención a defectos típicos con un criterio común', 'Garantiza encontrar todos los defectos', 'Solo sirve para código'],
      correct: 1,
      explanation: 'Ayuda a no olvidar defectos típicos, pero no garantiza encontrarlo todo.',
    },
  ],
}
