import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulos 2.1.3 y 4.5). */
export const m02Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m2pre_3c',
      conceptId: 'user_story',
      question: 'En las 3C de una historia de usuario, ¿qué representa la «confirmación»? (K1)',
      options: ['La tarjeta con el texto «Como… quiero… para…»', 'Los criterios de aceptación', 'La aprobación del manager', 'La estimación en puntos'],
      correct: 1,
      explanation: 'Card, conversation y confirmation: la confirmación son los criterios de aceptación.',
    },
    {
      id: 'c2m2pre_criteria',
      conceptId: 'acceptance_criteria',
      question: '¿Cuál de estos criterios de aceptación es verificable? (K2)',
      options: ['El pago debe ser rápido', 'La pantalla debe ser intuitiva', 'Un enlace pagado rechaza un segundo pago con el motivo «enlace ya pagado»', 'El sistema debe funcionar correctamente'],
      correct: 2,
      explanation: 'Solo el tercero define un resultado observable y comprobable.',
    },
    {
      id: 'c2m2pre_atdd',
      conceptId: 'atdd',
      question: 'En ATDD, ¿cuándo se escriben las pruebas de aceptación? (K1)',
      options: ['Después de la implementación, en pruebas de sistema', 'Antes de implementar la historia, a partir de sus criterios', 'Solo cuando aparece un defecto', 'En producción'],
      correct: 1,
      explanation: 'ATDD es test-first: los casos de aceptación se definen antes de programar.',
    },
    {
      id: 'c2m2pre_gherkin',
      conceptId: 'bdd',
      question: '¿Qué escenario sigue mejor las buenas prácticas de BDD? (K2)',
      options: [
        'Dado que estoy en «Mis enlaces», Cuando hago clic en «Pagar» y pulso «Confirmar», Entonces veo un mensaje verde',
        'Dado un enlace pagado, Cuando el cliente lo paga, Entonces el pago se rechaza con el motivo «enlace ya pagado»',
        'Dado un enlace, Cuando el cliente paga y el emisor lo anula, Entonces todo funciona correctamente',
        'Cuando pruebo el enlace, Entonces funciona',
      ],
      correct: 1,
      explanation: 'Declarativo, un solo Cuando y un Entonces verificable.',
    },
    {
      id: 'c2m2pre_tdd',
      conceptId: 'tdd',
      question: '¿Cuál es el orden correcto de un ciclo TDD? (K1)',
      options: ['Código, test, refactor', 'Test que falla, código mínimo que lo pasa, refactor', 'Refactor, test, código', 'Test que pasa, código, despliegue'],
      correct: 1,
      explanation: 'Rojo, verde, refactor.',
    },
    {
      id: 'c2m2pre_testfirst',
      conceptId: 'test_first',
      question: '¿Qué principio del testing aplican los enfoques test-first? (K2)',
      options: ['El testing exhaustivo es imposible', 'Testing temprano (shift-left)', 'Paradoja del pesticida', 'Agrupación de defectos'],
      correct: 1,
      explanation: 'Definen las pruebas antes del código: testing temprano.',
    },
  ],
  post: [
    {
      id: 'c2m2post_3c',
      conceptId: 'user_story',
      question: 'Una PO dice que la historia «ya está escrita en la tarjeta». ¿Qué parte de las 3C falta para conocer los detalles? (K2)',
      options: ['Card', 'Conversation', 'Confirmation', 'Ninguna'],
      correct: 1,
      explanation: 'Los detalles salen de la conversación en equipo; la tarjeta es solo un recordatorio.',
    },
    {
      id: 'c2m2post_criteria',
      conceptId: 'acceptance_criteria',
      question: '¿Cuál NO es un uso de los criterios de aceptación? (K2)',
      options: ['Definir el alcance de la historia', 'Llegar a un consenso entre las partes', 'Servir de base a las pruebas de aceptación', 'Demostrar que el software no tiene defectos'],
      correct: 3,
      explanation: 'Ninguna prueba demuestra la ausencia de defectos.',
    },
    {
      id: 'c2m2post_atdd',
      conceptId: 'atdd',
      question: 'En ATDD, tras el taller de especificación, ¿qué casos se suelen escribir primero? (K2)',
      options: ['Los no funcionales', 'Los positivos (comportamiento correcto sin excepciones)', 'Los de rendimiento', 'Los de regresión'],
      correct: 1,
      explanation: 'Primero los positivos, después los negativos y los no funcionales.',
    },
    {
      id: 'c2m2post_bva',
      conceptId: 'bdd',
      question: 'El importe permitido va de 1,00 € a 5.000,00 €. ¿Qué ejemplos del esquema aplican valores límite de dos puntos? (K3)',
      options: ['1,00 y 5.000,00', '0,99 / 1,00 / 5.000,00 / 5.000,01', '0 / 2.500 / 10.000', '1 / 100 / 1.000'],
      correct: 1,
      explanation: 'A cada lado de cada borde: 0,99 y 1,00; 5.000,00 y 5.000,01.',
    },
    {
      id: 'c2m2post_tdd',
      conceptId: 'tdd',
      question: 'En TDD, ¿cuándo se refactoriza? (K2)',
      options: ['Antes de escribir el test', 'Con los tests en rojo, para que pasen', 'Con todos los tests en verde, y se vuelven a ejecutar', 'Solo al final del proyecto'],
      correct: 2,
      explanation: 'El refactor se hace en verde y los tests confirman que nada se ha roto.',
    },
    {
      id: 'c2m2post_testfirst',
      conceptId: 'test_first',
      question: '¿Qué enfoque expresa el comportamiento en un lenguaje que negocio entiende, normalmente Dado/Cuando/Entonces? (K1)',
      options: ['TDD', 'BDD', 'Pruebas exploratorias', 'Pruebas de componente'],
      correct: 1,
      explanation: 'BDD (desarrollo guiado por el comportamiento).',
    },
  ],
}
