import type { Scene } from '../../../engine/types'

/** Escenas de la misión 2 del curso 2 (Dado, cuando, entonces). */
export const m02Scenes: Scene[] = [
  {
    id: 'mail_elena',
    channel: 'email',
    from: 'elena',
    at: 0,
    subject: 'KOB-E-21 · Cobro por enlace de pago',
    body: 'Buenos días 🙂\n\nOs paso la historia para la sesión de las 09:10: «Como autónomo, quiero enviar un enlace de pago a mi cliente para cobrar sin datáfono».\n\nEl enlace puede ser de 1 a 5.000 € y el cliente paga con tarjeta. Creo que con eso está todo.\n\nElena',
  },
  {
    id: 'mail_raul',
    channel: 'email',
    from: 'raul',
    at: 0,
    subject: 'Cómo trabajamos esta historia',
    body: 'Probamos ATDD con esta historia: lo que acordéis hoy como escenarios es el criterio de aceptación y se automatiza tal cual. Tomás empieza a programar a las 15:00.\n\nRaúl',
  },
  {
    id: 'amigos',
    channel: 'meeting',
    from: 'elena',
    with: ['tomas'],
    at: 10,
    subject: '09:10 · Tres amigos: cobro por enlace de pago',
    body: '**Elena:** La historia es sencilla: el autónomo crea el enlace y el cliente paga. Escribimos el caso feliz y listo, que vamos justos.\n\n**Tomás:** A mí con los límites de importe me basta.',
    choices: [
      {
        id: 'mapping',
        text: 'Hagamos un mapeo de ejemplos rápido: por cada regla, ejemplos concretos y las preguntas abiertas. ¿Qué pasa si el enlace caduca, si alguien lo paga dos veces o si el emisor lo anula?',
        cost: 30,
        reply: 'Vale… caduca a los 7 días, solo se puede pagar una vez y se puede anular mientras no esté pagado. No lo había escrito 😅',
        replyFrom: 'elena',
        effects: [
          { kind: 'flag', key: 'amigos.done' },
          { kind: 'flag', key: 'amigos.mapped' },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'unlock', conceptId: 'user_story' },
          { kind: 'note', tone: 'good', text: 'Hiciste que la conversación de los tres amigos sacara las reglas con ejemplos.' },
        ],
      },
      {
        id: 'happy',
        text: 'De acuerdo: caso feliz y límites de importe.',
        cost: 10,
        reply: '¡Genial, así acabamos antes!',
        replyFrom: 'elena',
        effects: [
          { kind: 'flag', key: 'amigos.done' },
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'user_story' },
          { kind: 'note', tone: 'bad', text: 'Te quedaste en el caso feliz: nadie preguntó por las reglas que no salen en la tarjeta.' },
        ],
      },
      {
        id: 'later',
        text: 'Escribidlo vosotros y yo lo pruebo cuando esté hecho.',
        cost: 5,
        reply: 'Ah… vale. Pensaba que esto iba de hacerlo juntos.',
        replyFrom: 'tomas',
        effects: [
          { kind: 'flag', key: 'amigos.done' },
          { kind: 'flag', key: 'amigos.absent' },
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'score', key: 'communication', add: -1 },
          { kind: 'unlock', conceptId: 'test_first' },
          { kind: 'note', tone: 'bad', text: 'Propusiste probar al final en lugar de definir las pruebas antes (test-last).' },
        ],
      },
    ],
  },
  {
    id: 'laura_mapped',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'amigos.mapped' },
    body: 'Muy bien la sesión 👌 Ahora convierte cada regla del mapa en escenarios en la app «Escenarios»: un comportamiento por escenario, nada de pantallas ni clics, y para el importe un esquema con ejemplos justo en los bordes. La guía BDD está en la wiki.',
    onDeliver: [{ kind: 'unlock', conceptId: 'acceptance_criteria' }],
  },
  {
    id: 'laura_absent',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'amigos.absent' },
    body: '¿«Lo pruebo cuando esté hecho»? Con ATDD es al revés: las pruebas de aceptación se escriben antes del código, juntos. Aún estás a tiempo de escribir los escenarios en la app.',
    onDeliver: [{ kind: 'unlock', conceptId: 'atdd' }],
  },
  {
    id: 'sofia_tdd',
    channel: 'chat',
    from: 'sofia',
    at: 90,
    when: { kind: 'flag', key: 'amigos.done' },
    body: '¡Hola! Me toca la comisión del enlace: 1,4 % del importe con un mínimo de 0,25 €. Laura dice que la hagamos con TDD contigo. ¿Te vienes? Está en la pestaña «TDD con Sofía» de Escenarios.',
    onDeliver: [
      { kind: 'flag', key: 'sofia.asked' },
      { kind: 'unlock', conceptId: 'tdd' },
    ],
  },
  {
    id: 'sofia_codefirst',
    channel: 'chat',
    from: 'sofia',
    when: { kind: 'flag', key: 'tdd.code_first' },
    body: 'Uy, he escrito el código antes que ningún test… Eso ya no es TDD, ¿no? 😅',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: -1 },
      { kind: 'unlock', conceptId: 'tdd' },
      { kind: 'note', tone: 'bad', text: 'En TDD escribisteis código antes que el test.' },
    ],
  },
  {
    id: 'sofia_refactor_red',
    channel: 'chat',
    from: 'sofia',
    when: { kind: 'flag', key: 'tdd.refactor_red' },
    body: '¿Refactorizar con tests en rojo o sin ejecutar? Así no sabemos si el cambio rompe algo…',
    onDeliver: [{ kind: 'note', tone: 'bad', text: 'Refactorizasteis sin tener los tests en verde.' }],
  },
  {
    id: 'sofia_cycle',
    channel: 'chat',
    from: 'sofia',
    when: { kind: 'flag', key: 'tdd.cycle' },
    body: '¡Rojo, verde, refactor! Y el test del mínimo ha salido del propio ciclo: sin él, habría cobrado 0,07 € en un enlace de 5 €. Me lo apunto 💡',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: 1 },
      { kind: 'note', tone: 'good', text: 'Completaste con Sofía un ciclo TDD: test en rojo, código mínimo en verde y refactor con los tests en verde.' },
    ],
  },
  {
    id: 'elena_happy',
    channel: 'chat',
    from: 'elena',
    at: 150,
    when: { kind: 'notFlag', key: 'gk.agreed' },
    body: '¿Cómo lo lleváis? Con dos o tres escenarios del caso feliz nos sobra, ¿eh? Que a las 15:00 Tomás empieza 😉',
  },
  {
    id: 'laura_time',
    channel: 'chat',
    from: 'laura',
    at: 300,
    when: { kind: 'notFlag', key: 'gk.agreed' },
    body: 'Recuerda: a las 15:00 Tomás programa a partir de los escenarios acordados. Si no hay acuerdo, programará lo que entendió.',
  },
  {
    id: 'agreed_good',
    channel: 'chat',
    from: 'tomas',
    when: { kind: 'flag', key: 'gk.style' },
    body: 'Así da gusto: cada escenario es un comportamiento y lo puedo automatizar tal cual. Y los ejemplos de importe me quitan la duda de «menor» o «menor o igual».',
    onDeliver: [
      { kind: 'score', key: 'communication', add: 1 },
      { kind: 'score', key: 'rigor', add: 1 },
      { kind: 'unlock', conceptId: 'bdd' },
      { kind: 'note', tone: 'good', text: 'Acordaste escenarios claros: un comportamiento por escenario, sin pantallas y con resultados verificables.' },
    ],
  },
  {
    id: 'agreed_ui',
    channel: 'chat',
    from: 'tomas',
    when: { kind: 'flag', key: 'gk.ui' },
    body: 'Si automatizo «hago clic en Pagar y relleno la tarjeta», el día que cambie la pantalla se nos rompen todos los escenarios. ¿No sería mejor describir qué pasa y no cómo se pulsa?',
    onDeliver: [
      { kind: 'unlock', conceptId: 'bdd' },
      { kind: 'note', tone: 'bad', text: 'Algunos escenarios describían la interfaz en lugar del comportamiento.' },
    ],
  },
  {
    id: 'agreed_wrong',
    channel: 'chat',
    from: 'elena',
    when: { kind: 'flag', key: 'gk.wrong' },
    body: 'Oye, en algún escenario el resultado esperado no es lo que dijimos en la reunión… Si eso se automatiza, el test «verde» comprobará justo lo contrario.',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: -1 },
      { kind: 'note', tone: 'bad', text: 'Acordaste escenarios con resultados esperados incorrectos.' },
    ],
  },
  {
    id: 'handoff',
    channel: 'chat',
    from: 'tomas',
    at: 360,
    body: 'Son las 15:00: empiezo a programar con los escenarios acordados como criterios de aceptación. Lo que no esté en un escenario, lo decido yo 🤷',
    onDeliver: [
      {
        kind: 'if',
        when: { kind: 'notFlag', key: 'gk.agreed' },
        then: [
          { kind: 'score', key: 'risk', add: -2 },
          { kind: 'note', tone: 'bad', text: 'A las 15:00 no había escenarios acordados: el desarrollo empezó sin criterios de aceptación.' },
        ],
        else: [{ kind: 'score', key: 'efficiency', add: 2 }],
      },
      { kind: 'if', when: { kind: 'flag', key: 'tdd.min' }, then: [{ kind: 'score', key: 'efficiency', add: 1 }] },
      {
        kind: 'if',
        when: { kind: 'all', of: [{ kind: 'flag', key: 'gk.r1min' }, { kind: 'flag', key: 'gk.r1max' }] },
        then: [{ kind: 'score', key: 'rigor', add: 1 }],
      },
      {
        kind: 'if',
        when: { kind: 'all', of: [{ kind: 'flag', key: 'gk.r2' }, { kind: 'flag', key: 'gk.r3' }, { kind: 'flag', key: 'gk.r4' }, { kind: 'flag', key: 'gk.r5' }] },
        then: [
          { kind: 'score', key: 'risk', add: 2 },
          { kind: 'note', tone: 'good', text: 'Todas las reglas del mapa de ejemplos llegaron a desarrollo como escenarios, incluidos los negativos.' },
        ],
      },
      { kind: 'preventBugs' },
    ],
  },
  {
    id: 'demo_double',
    channel: 'chat',
    from: 'elena',
    at: 450,
    when: { kind: 'notFlag', key: 'gk.r3' },
    body: 'He probado el prototipo: he pagado dos veces el mismo enlace… ¡y me ha cobrado las dos! 😱 ¿Eso no lo habíamos hablado?',
  },
  {
    id: 'demo',
    channel: 'meeting',
    from: 'raul',
    with: ['elena', 'tomas'],
    at: 450,
    subject: '16:30 · Demo del prototipo',
    body: '**Tomás:** El prototipo pasa todos los escenarios automatizados ✅\n\n**Raúl:** Entonces, ¿está lista para pruebas de sistema?',
    choices: [
      {
        id: 'honest',
        text: 'Los escenarios en verde dicen que se cumplen los criterios que acordamos, no que no haya defectos. Os enseño qué reglas cubren y qué queda fuera: eso es lo que probaremos en sistema.',
        cost: 10,
        reply: 'Me gusta saber qué está cubierto y qué no. Adelante.',
        replyFrom: 'raul',
        effects: [
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'unlock', conceptId: 'atdd' },
          { kind: 'note', tone: 'good', text: 'Explicaste que los escenarios en verde demuestran los criterios acordados, no la ausencia de defectos.' },
        ],
      },
      {
        id: 'green',
        text: 'Si los escenarios pasan, está todo bien.',
        cost: 5,
        reply: 'Perfecto, pues a producción en cuanto se pueda.',
        replyFrom: 'raul',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'atdd' },
          { kind: 'note', tone: 'bad', text: 'Diste por hecho que unos escenarios en verde significan que no hay defectos.' },
        ],
      },
    ],
  },
  {
    id: 'closing',
    channel: 'meeting',
    from: 'laura',
    at: 480,
    subject: '17:00 · Café con Laura',
    body: '**Laura:** ¿Qué te llevas de tu primera historia con ATDD?',
    choices: [
      {
        id: 'lesson',
        text: 'Que las pruebas se diseñan antes del código y en equipo: la conversación saca las reglas, los ejemplos fijan los bordes y los escenarios son a la vez especificación y test.',
        requires: { kind: 'flag', key: 'gk.agreed' },
        reply: 'Eso es. Y con TDD, lo mismo pero a nivel de código.',
        effects: [{ kind: 'score', key: 'communication', add: 1 }, { kind: 'endMission' }],
      },
      {
        id: 'waste',
        text: 'Que escribir escenarios antes del código es mucho papeleo.',
        reply: 'Mira en el debrief qué se programó mal por no estar en un escenario.',
        effects: [{ kind: 'note', tone: 'neutral', text: 'Te quedaste con el coste de escribir escenarios, no con su retorno.' }, { kind: 'endMission' }],
      },
    ],
  },
]
