import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulos 4.3 y 2.2.1). */
export const m03Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m3pre_stmt',
      conceptId: 'statement_cov',
      question: 'Un componente tiene 10 sentencias ejecutables y la suite ejecuta 8. ¿Cuál es la cobertura de sentencias? (K3)',
      options: ['8 %', '80 %', '100 %', 'No se puede saber sin conocer las ramas'],
      correct: 1,
      explanation: '8 ÷ 10 = 80 %.',
    },
    {
      id: 'c2m3pre_branch',
      conceptId: 'branch_cov',
      question: '¿Qué afirmación es correcta? (K2)',
      options: [
        '100 % de sentencias implica 100 % de ramas',
        '100 % de ramas implica 100 % de sentencias',
        'Son equivalentes',
        'Ninguna implica la otra',
      ],
      correct: 1,
      explanation: 'Recorrer todas las ramas obliga a ejecutar todas las sentencias; al revés, no.',
    },
    {
      id: 'c2m3pre_limits',
      conceptId: 'coverage_limits',
      question: 'Una suite con 100 % de cobertura de sentencias no detecta un bug conocido. ¿Cuál es la explicación más probable? (K2)',
      options: ['La herramienta de cobertura falla', 'Algún test pasa por el defecto pero no comprueba el resultado', 'El bug está en el compilador', 'Con 100 % es imposible'],
      correct: 1,
      explanation: 'La cobertura mide lo ejecutado, no lo comprobado.',
    },
    {
      id: 'c2m3pre_wb',
      conceptId: 'white_box',
      question: '¿Qué tipo de defecto NO pueden detectar por sí solas las técnicas de caja blanca? (K2)',
      options: ['Una condición mal escrita', 'Un requisito que no se ha implementado', 'Una sentencia con un cálculo erróneo', 'Una rama que nunca se ejecuta'],
      correct: 1,
      explanation: 'Si un requisito falta, no hay código que cubrir.',
    },
    {
      id: 'c2m3pre_comp',
      conceptId: 'component_testing',
      question: '¿Quién suele escribir las pruebas de componente? (K1)',
      options: ['El cliente', 'Los desarrolladores', 'Compliance', 'Operaciones'],
      correct: 1,
      explanation: 'Normalmente los desarrolladores, en su entorno.',
    },
    {
      id: 'c2m3pre_count',
      conceptId: 'branch_cov',
      question: 'Un código tiene un único «si» sin «sino». ¿Cuántas ramas hay que cubrir para el 100 % de ramas? (K3)',
      options: ['1', '2', '3', '0'],
      correct: 1,
      explanation: 'Verdadera y falsa, aunque la falsa no tenga sentencias.',
    },
  ],
  post: [
    {
      id: 'c2m3post_stmt',
      conceptId: 'statement_cov',
      question: 'Con 100 % de cobertura de sentencias, ¿qué se puede afirmar? (K2)',
      options: [
        'Que no hay defectos',
        'Que cada sentencia se ejecutó al menos una vez',
        'Que se probaron todas las ramas',
        'Que todos los resultados se comprobaron',
      ],
      correct: 1,
      explanation: 'Solo que cada sentencia ejecutable se ejecutó al menos una vez.',
    },
    {
      id: 'c2m3post_calc',
      conceptId: 'branch_cov',
      question: 'Un código tiene 3 decisiones (6 ramas). La suite recorre 5. ¿Cobertura de ramas? (K3)',
      options: ['50 %', '83 %', '100 %', '60 %'],
      correct: 1,
      explanation: '5 ÷ 6 ≈ 83 %.',
    },
    {
      id: 'c2m3post_assert',
      conceptId: 'coverage_limits',
      question: 'Un compañero propone añadir tests sin aserciones para llegar al 100 %. ¿Cuál es el problema? (K2)',
      options: ['Ninguno', 'Aumentan la cobertura sin detectar defectos', 'Bajan la cobertura de ramas', 'Rompen el pipeline'],
      correct: 1,
      explanation: 'Ejecutan código pero no comprueban nada.',
    },
    {
      id: 'c2m3post_oracle',
      conceptId: 'coverage_limits',
      question: '¿De dónde debe salir el resultado esperado de un caso de prueba? (K2)',
      options: ['De lo que devuelve el código', 'De la especificación o de otra fuente de verdad (oráculo)', 'De la herramienta de cobertura', 'De la última versión en producción, siempre'],
      correct: 1,
      explanation: 'Copiarlo del código convierte el bug en el comportamiento esperado.',
    },
    {
      id: 'c2m3post_wb',
      conceptId: 'white_box',
      question: '¿Cuál es un beneficio de las técnicas de caja blanca? (K2)',
      options: ['Detectan requisitos que faltan', 'Se pueden usar aunque la especificación sea vaga, y miden lo que la suite ha ejecutado', 'No necesitan acceso al código', 'Sustituyen a las pruebas de aceptación'],
      correct: 1,
      explanation: 'Se basan en la implementación y dan una medida objetiva de la cobertura.',
    },
    {
      id: 'c2m3post_comp',
      conceptId: 'component_testing',
      question: '¿Qué suelen necesitar las pruebas de componente para aislar el componente? (K1)',
      options: ['Usuarios reales', 'Stubs, drivers o simuladores', 'Un entorno de producción', 'Un contrato firmado'],
      correct: 1,
      explanation: 'Sustituyen a los componentes de los que depende o lo invocan.',
    },
  ],
}
