import type { Scene } from '../../../engine/types'

/** Escenas de la misión 3 del curso 2 (Dentro del código). */
export const m03Scenes: Scene[] = [
  {
    id: 'mail_carmen',
    channel: 'email',
    from: 'carmen',
    at: 0,
    subject: 'Facturas con retención incorrecta',
    body: 'Hola. Tres clientes nos han escrito: sus facturas a empresas salen con una retención de IRPF ridícula, como del 1,5 %. Los tres son autónomos que llevan años con nosotros. Hacienda no perdona esto: necesito saber qué pasa y que no vuelva a ocurrir.\n\nCarmen · Riesgos y Compliance',
  },
  {
    id: 'mail_raul',
    channel: 'email',
    from: 'raul',
    at: 0,
    subject: 'Módulo de facturas',
    body: 'Mira lo de Carmen con Tomás. Él dice que el módulo de cálculo tiene «100 % de cobertura», así que el problema estará en otra parte. Tienes el código y su suite en la app «Cobertura».\n\nRaúl',
  },
  {
    id: 'tomas_coverage',
    channel: 'meeting',
    from: 'tomas',
    with: ['sofia'],
    at: 15,
    subject: '09:15 · Tomás: «tenemos 100 % de cobertura»',
    body: '**Tomás:** El cálculo está cubierto al 100 %, lo dice el informe de cobertura. El fallo tiene que estar en la generación del PDF. ¿Lo miras por ahí?',
    choices: [
      {
        id: 'inspect',
        text: 'El 100 % es de sentencias: dice qué líneas se ejecutaron, no si alguien comprobó el resultado, y no garantiza que se hayan probado todas las ramas. Déjame mirar la suite antes de descartar el cálculo.',
        cost: 10,
        reply: 'Vale… mira, pero ya verás que está todo verde.',
        replyFrom: 'tomas',
        effects: [
          { kind: 'flag', key: 'coverage.questioned' },
          { kind: 'score', key: 'rigor', add: 1 },
          { kind: 'unlock', conceptId: 'statement_cov' },
          { kind: 'note', tone: 'good', text: 'No aceptaste un porcentaje de cobertura como prueba de calidad.' },
        ],
      },
      {
        id: 'pdf',
        text: 'Si está cubierto al 100 %, miro el PDF.',
        cost: 60,
        reply: 'Eso, eso.',
        replyFrom: 'tomas',
        effects: [
          { kind: 'score', key: 'efficiency', add: -1 },
          { kind: 'score', key: 'rigor', add: -1 },
          { kind: 'unlock', conceptId: 'statement_cov' },
          { kind: 'note', tone: 'bad', text: 'Diste por bueno el «100 % de cobertura» y perdiste una hora revisando el PDF.' },
        ],
      },
    ],
  },
  {
    id: 'laura_hint',
    channel: 'chat',
    from: 'laura',
    at: 60,
    when: { kind: 'notFlag', key: 'cov.t3_asserted' },
    body: 'Truco: mira qué casos de la suite tienen la casilla «Comprueba» marcada y qué ramas (V/F) quedan en rojo al ejecutar. La especificación del cálculo está en la wiki, por si tienes que calcular resultados esperados.',
    onDeliver: [{ kind: 'unlock', conceptId: 'branch_cov' }],
  },
  {
    id: 'sofia_noassert',
    channel: 'meeting',
    from: 'sofia',
    at: 150,
    subject: '11:30 · Sofía: una idea para la cobertura',
    body: '**Sofía:** Tomás me ha pedido que suba la cobertura del resto del módulo al 100 %. He pensado añadir tests que llamen a las funciones sin comprobar nada; son rapidísimos. ¿Te parece bien?',
    choices: [
      {
        id: 'assert',
        text: 'Mejor no: un test sin aserción «cubre» pero no detecta nada, como el caso #3 de Tomás, que pasa por la línea del bug y sale verde. Cada test tiene que comprobar un resultado esperado sacado de la especificación.',
        cost: 5,
        reply: '¡Ostras, el #3! Entendido: menos tests, pero que comprueben algo.',
        replyFrom: 'sofia',
        effects: [
          { kind: 'flag', key: 'coverage.assert_lesson' },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'score', key: 'rigor', add: 1 },
          { kind: 'unlock', conceptId: 'coverage_limits' },
          { kind: 'note', tone: 'good', text: 'Explicaste que la cobertura mide lo ejecutado, no lo comprobado.' },
        ],
      },
      {
        id: 'ok',
        text: 'Vale, si sube el número, adelante.',
        cost: 5,
        reply: '¡Hecho! 100 % en una tarde 🎉',
        replyFrom: 'sofia',
        effects: [
          { kind: 'score', key: 'rigor', add: -1 },
          { kind: 'unlock', conceptId: 'coverage_limits' },
          { kind: 'note', tone: 'bad', text: 'Aceptaste tests sin aserciones para inflar la cobertura.' },
        ],
      },
    ],
  },
  {
    id: 'laura_bug_found',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'bugTriggered', bugId: 'B-RET' },
    body: 'Ese caso en rojo es el bug de Carmen: el caso #3 ya pasaba por esa línea, pero sin comprobar nada. Repórtalo en el tablero adjuntando la ejecución como evidencia.',
    onDeliver: [{ kind: 'unlock', conceptId: 'coverage_limits' }],
  },
  {
    id: 'laura_branch100',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'cov.branch100' },
    body: '100 % de ramas 👌 Fíjate: con 100 % de sentencias faltaba la rama falsa de «si base > 3000». Una decisión sin «sino» tiene una rama que no añade sentencias, y solo la cobertura de ramas la ve.',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: 1 },
      { kind: 'unlock', conceptId: 'branch_cov' },
      { kind: 'note', tone: 'good', text: 'Llevaste la suite al 100 % de ramas, no solo de sentencias.' },
    ],
  },
  {
    id: 'carmen_rev',
    channel: 'chat',
    from: 'carmen',
    when: { kind: 'bugTriggered', bugId: 'B-REV' },
    body: '¿Una factura de 3.000 € justos no pasa a revisión? La norma interna dice «3.000 € o más». Buen hallazgo: ese ni lo teníamos en el radar.',
    onDeliver: [{ kind: 'score', key: 'risk', add: 1 }],
  },
  {
    id: 'pipeline',
    channel: 'meeting',
    from: 'raul',
    with: ['tomas', 'laura'],
    at: 390,
    subject: '15:30 · Raúl: umbral de cobertura en el pipeline',
    body: '**Raúl:** Después de lo de hoy quiero poner un umbral de cobertura en el pipeline. ¿Qué propones?',
    choices: [
      {
        id: 'branches',
        text: 'Un mínimo de cobertura de ramas en el código crítico (cálculos, pagos), revisión de que los tests comprueben resultados y casos en los límites. La cobertura es un indicador de lo que falta por probar, no una garantía de calidad.',
        cost: 10,
        reply: 'Me gusta: el número nos dice dónde mirar, no que esté bien.',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'unlock', conceptId: 'white_box' },
          { kind: 'note', tone: 'good', text: 'Propusiste usar la cobertura de ramas como indicador, junto a aserciones y valores límite.' },
        ],
      },
      {
        id: 'stmt90',
        text: '90 % de sentencias en todo el código y listo.',
        cost: 5,
        reply: 'Hoy teníamos 100 % de sentencias y dos bugs…',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'white_box' },
          { kind: 'note', tone: 'bad', text: 'Propusiste un umbral de sentencias como garantía de calidad.' },
        ],
      },
    ],
  },
  {
    id: 'closing',
    channel: 'meeting',
    from: 'laura',
    at: 480,
    subject: '17:00 · Café con Laura',
    body: '**Laura:** ¿Qué te llevas de tu día dentro del código?',
    choices: [
      {
        id: 'lesson',
        text: 'Que la cobertura dice qué se ejecutó, no qué se comprobó; que 100 % de sentencias no es 100 % de ramas; y que la caja blanca sirve para encontrar lo que nadie ha probado, no para presumir de un número.',
        reply: 'Eso es. Y mañana, a por lo que no está en el código: la exploración.',
        effects: [{ kind: 'score', key: 'communication', add: 1 }, { kind: 'endMission' }],
      },
      {
        id: 'number',
        text: 'Que hay que tener la cobertura al 100 %.',
        reply: 'El caso #3 estaba al 100 % y no detectaba nada. Míralo en el debrief.',
        effects: [{ kind: 'note', tone: 'neutral', text: 'Te quedaste con el número de cobertura, no con lo que mide.' }, { kind: 'endMission' }],
      },
    ],
  },
]
