import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulo 4.4). */
export const m04Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m4pre_eg',
      conceptId: 'error_guessing',
      question: '¿En qué se basa la predicción de errores? (K1)',
      options: ['En la estructura del código', 'En el conocimiento de errores, defectos y fallos ocurridos antes', 'En los requisitos formales', 'En la cobertura de ramas'],
      correct: 1,
      explanation: 'Se anticipan fallos a partir de la experiencia.',
    },
    {
      id: 'c2m4pre_exp',
      conceptId: 'exploratory',
      question: '¿Qué caracteriza a las pruebas exploratorias? (K2)',
      options: ['Se diseñan todas antes de ejecutar', 'Diseño, ejecución y evaluación ocurren a la vez mientras se aprende', 'Solo las hacen usuarios finales', 'No permiten tomar notas'],
      correct: 1,
      explanation: 'Se aprende del objeto de prueba mientras se prueba.',
    },
    {
      id: 'c2m4pre_charter',
      conceptId: 'exploratory',
      question: 'En una sesión exploratoria, ¿qué es el charter? (K1)',
      options: ['El informe final', 'El objetivo de la sesión', 'La lista de bugs', 'El contrato con el cliente'],
      correct: 1,
      explanation: 'El charter fija el objetivo de la sesión.',
    },
    {
      id: 'c2m4pre_when',
      conceptId: 'exploratory',
      question: '¿Cuándo son especialmente útiles las pruebas exploratorias? (K2)',
      options: ['Cuando hay especificaciones completas y mucho tiempo', 'Cuando la especificación es pobre o hay presión de tiempo', 'Solo en pruebas de componente', 'Nunca en entornos regulados'],
      correct: 1,
      explanation: 'Encajan con poca documentación o poco tiempo.',
    },
    {
      id: 'c2m4pre_cl',
      conceptId: 'checklist_based',
      question: '¿Cuál es un riesgo de usar siempre la misma checklist? (K2)',
      options: ['Que sea demasiado detallada', 'Que deje de encontrar defectos nuevos', 'Que no se pueda automatizar', 'Ninguno'],
      correct: 1,
      explanation: 'Hay que mantenerla viva.',
    },
    {
      id: 'c2m4pre_xb',
      conceptId: 'experience_based',
      question: '¿Qué relación tienen las técnicas basadas en la experiencia con las de caja negra y blanca? (K2)',
      options: ['Las sustituyen', 'Las complementan', 'Son incompatibles', 'Solo se usan si fallan las otras'],
      correct: 1,
      explanation: 'Son complementarias.',
    },
  ],
  post: [
    {
      id: 'c2m4post_attack',
      conceptId: 'error_guessing',
      question: 'Un tester prueba a enviar dos veces el formulario y a dejar caducar la sesión antes de confirmar. ¿Qué técnica aplica? (K2)',
      options: ['Partición de equivalencia', 'Predicción de errores (ataques de fallos)', 'Cobertura de ramas', 'Pruebas de aceptación'],
      correct: 1,
      explanation: 'Son ataques típicos de predicción de errores.',
    },
    {
      id: 'c2m4post_session',
      conceptId: 'exploratory',
      question: '¿Qué hace gestionables las pruebas exploratorias? (K2)',
      options: ['Prohibir las notas', 'Sesiones con charter, timebox e informe', 'Hacerlas sin objetivo', 'Ejecutarlas solo al final del proyecto'],
      correct: 1,
      explanation: 'Las sesiones con charter y tiempo permiten planificar y medir.',
    },
    {
      id: 'c2m4post_cl',
      conceptId: 'checklist_based',
      question: 'Una checklist escrita hace un año da todo en verde en una versión con tres funciones nuevas. ¿Qué conclusión es correcta? (K2)',
      options: ['La versión no tiene defectos', 'La checklist no cubre lo nuevo y hay que complementarla y actualizarla', 'Hay que borrar la checklist', 'Las funciones nuevas no necesitan pruebas'],
      correct: 1,
      explanation: 'Una checklist no ve lo que no conoce.',
    },
    {
      id: 'c2m4post_exp',
      conceptId: 'exploratory',
      question: '¿Qué debe incluir un informe de sesión exploratoria? (K2)',
      options: ['Solo los bugs', 'Qué se cubrió, qué se encontró y qué queda pendiente', 'Solo el tiempo usado', 'Nada: la exploración no se documenta'],
      correct: 1,
      explanation: 'Permite seguir y repartir la exploración.',
    },
    {
      id: 'c2m4post_xb',
      conceptId: 'experience_based',
      question: '¿De qué depende sobre todo la eficacia de las técnicas basadas en la experiencia? (K1)',
      options: ['De la herramienta', 'De la experiencia y el conocimiento de quien las aplica', 'Del lenguaje de programación', 'Del número de casos'],
      correct: 1,
      explanation: 'Su eficacia depende de la persona.',
    },
    {
      id: 'c2m4post_eg2',
      conceptId: 'error_guessing',
      question: '¿Qué fuente NO es típica para predecir errores? (K1)',
      options: ['Fallos anteriores de la aplicación', 'Errores típicos de los desarrolladores', 'Fallos de aplicaciones parecidas', 'El color corporativo de la empresa'],
      correct: 3,
      explanation: 'Las otras tres son fuentes clásicas.',
    },
  ],
}
