import type { Scene } from '../../../engine/types'

/** Escenas de la misión 4 del curso 2 (Intuición experta). */
export const m04Scenes: Scene[] = [
  {
    id: 'mail_raul',
    channel: 'email',
    from: 'raul',
    at: 0,
    subject: 'Tarjetas de equipo v2: ¿sale el viernes?',
    body: 'La v2 del panel de Tarjetas de equipo está en staging. Documentación, poca: lo que hay son las notas de versión de Elena en la wiki. A las 13:00 decidimos si sale el viernes y quiero tu valoración.\n\nRaúl',
  },
  {
    id: 'mail_elena',
    channel: 'email',
    from: 'elena',
    at: 0,
    subject: 'Lo que más usan los admins',
    body: 'Por si te sirve: lo que más nos piden los administradores de las pymes es congelar al momento una tarjeta perdida. Y con la v2 por fin pueden hacerlo desde el panel. 🙌\n\nElena',
  },
  {
    id: 'approach',
    channel: 'meeting',
    from: 'laura',
    at: 10,
    subject: '09:10 · Laura: ¿cómo lo enfocas?',
    body: '**Laura:** Poca documentación, poco tiempo y una decisión a las 13:00. ¿Cómo vas a probar la v2?',
    choices: [
      {
        id: 'sessions',
        text: 'Sesiones exploratorias cortas, cada una con su charter: primero lo nuevo y lo que más riesgo tiene (congelar, invitar, exportar), con ataques de predicción de errores. Y paso la checklist del equipo como base.',
        cost: 5,
        reply: 'Eso es. Exploratoria no es «ir clicando»: es aprender, diseñar y ejecutar a la vez, pero con un objetivo y un tiempo.',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'rigor', add: 1 },
          { kind: 'score', key: 'risk', add: 1 },
          { kind: 'unlock', conceptId: 'exploratory' },
          { kind: 'note', tone: 'good', text: 'Planteaste sesiones exploratorias con charter, centradas en lo nuevo y arriesgado.' },
        ],
      },
      {
        id: 'checklist',
        text: 'Paso la checklist del equipo y, si sale verde, adelante.',
        cost: 5,
        reply: 'La checklist es una base, pero se escribió antes de la v2. No sabe nada de lo nuevo.',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'unlock', conceptId: 'checklist_based' },
          { kind: 'note', tone: 'bad', text: 'Pensaste fiarlo todo a una checklist escrita antes de las novedades.' },
        ],
      },
      {
        id: 'click',
        text: 'Voy clicando por todo a ver qué sale.',
        cost: 5,
        reply: 'Sin charter ni tiempo, se va la mañana y no sabrás qué has cubierto.',
        replyFrom: 'laura',
        effects: [
          { kind: 'score', key: 'rigor', add: -1 },
          { kind: 'unlock', conceptId: 'exploratory' },
          { kind: 'note', tone: 'bad', text: 'Ibas a explorar sin objetivo ni tiempo.' },
        ],
      },
    ],
  },
  {
    id: 'tomas_checklist',
    channel: 'chat',
    from: 'tomas',
    at: 45,
    body: 'Por cierto, la checklist del equipo ya la pasé yo ayer: todo en verde ✅. Yo no perdería mucho tiempo.',
  },
  {
    id: 'laura_nocharter',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'explore.nocharter' },
    body: 'Te veo atacando fuera de un charter (o con la sesión agotada). Cada ataque así cuesta más y no queda en ningún informe. Abre una sesión con su charter y su tiempo.',
    onDeliver: [
      { kind: 'score', key: 'efficiency', add: -1 },
      { kind: 'unlock', conceptId: 'exploratory' },
      { kind: 'note', tone: 'bad', text: 'Exploraste sin charter o fuera del tiempo de la sesión.' },
    ],
  },
  {
    id: 'laura_report',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'session.report' },
    body: 'Buen informe de sesión: qué exploraste, cuánto tiempo, qué encontraste y qué queda pendiente. Eso es lo que hace que la exploración sea gestionable.',
    onDeliver: [
      { kind: 'score', key: 'communication', add: 1 },
      { kind: 'unlock', conceptId: 'exploratory' },
      { kind: 'note', tone: 'good', text: 'Cerraste cada sesión con su informe.' },
    ],
  },
  {
    id: 'laura_session_bug',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'bugTriggered', bugId: 'X-SESION' },
    body: '¡Eso es gordo! Un admin que pierde una tarjeta, la «congela» con la sesión caducada… y la tarjeta sigue pagando. Repórtalo ya, con la nota como evidencia.',
    onDeliver: [{ kind: 'unlock', conceptId: 'error_guessing' }],
  },
  {
    id: 'gonogo',
    channel: 'meeting',
    from: 'raul',
    with: ['elena', 'tomas'],
    at: 240,
    subject: '13:00 · Go / no-go de Tarjetas de equipo v2',
    body: '**Raúl:** La checklist está en verde, según Tomás. ¿Sale el viernes?',
    choices: [
      {
        id: 'nogo',
        text: 'No-go para el viernes: con la sesión caducada, «Congelar» dice que congela y no lo hace, que es justo lo que más usan los admins. El resto de bugs tienen fecha y no bloquean. En cuanto esté corregido y verificado, sale.',
        requires: { kind: 'bugReported', bugId: 'X-SESION' },
        cost: 10,
        reply: 'Prefiero retrasar una semana a que una pyme pierda dinero con una tarjeta «congelada». No-go.',
        replyFrom: 'raul',
        effects: [
          { kind: 'flag', key: 'gonogo.right' },
          { kind: 'score', key: 'risk', add: 2 },
          { kind: 'score', key: 'communication', add: 1 },
          { kind: 'note', tone: 'good', text: 'Recomendaste no-go con un argumento de riesgo concreto y verificable.' },
        ],
      },
      {
        id: 'go_list',
        text: 'Go, con la lista de bugs que he encontrado para corregir después.',
        requires: { kind: 'reportsGte', value: 1 },
        cost: 10,
        reply: 'Vale… pero ¿alguno de esos bugs bloquea algo importante?',
        replyFrom: 'elena',
        effects: [
          { kind: 'score', key: 'risk', add: -1 },
          { kind: 'note', tone: 'neutral', text: 'Diste el go sin valorar qué bugs bloqueaban la salida.' },
        ],
      },
      {
        id: 'go',
        text: 'Go: la checklist está en verde.',
        cost: 5,
        reply: 'Perfecto, sale el viernes.',
        replyFrom: 'raul',
        effects: [
          { kind: 'score', key: 'risk', add: -2 },
          { kind: 'unlock', conceptId: 'checklist_based' },
          { kind: 'note', tone: 'bad', text: 'Diste el go porque la checklist estaba en verde: una checklist no ve lo que no conoce.' },
        ],
      },
    ],
  },
  {
    id: 'laura_checklist',
    channel: 'chat',
    from: 'laura',
    at: 330,
    when: { kind: 'notFlag', key: 'checklist.updated' },
    body: 'Antes de irte: la checklist del equipo no habría encontrado nada de lo de hoy. ¿La mejoramos con los ataques que te han funcionado? Está en la app «Exploración».',
    onDeliver: [{ kind: 'unlock', conceptId: 'checklist_based' }],
  },
  {
    id: 'checklist_improved',
    channel: 'chat',
    from: 'laura',
    when: { kind: 'flag', key: 'checklist.improved' },
    body: 'Checklist actualizada con lo que de verdad encuentra fallos. Así la intuición de hoy se convierte en conocimiento del equipo 👌',
    onDeliver: [
      { kind: 'score', key: 'rigor', add: 1 },
      { kind: 'unlock', conceptId: 'checklist_based' },
      { kind: 'note', tone: 'good', text: 'Mejoraste la checklist con los ataques que encontraron bugs.' },
    ],
  },
  {
    id: 'closing',
    channel: 'meeting',
    from: 'laura',
    at: 480,
    subject: '17:00 · Café con Laura',
    body: '**Laura:** ¿Qué te llevas de hoy?',
    choices: [
      {
        id: 'lesson',
        text: 'Que la experiencia se puede aplicar con método: charter y tiempo para explorar, una lista de ataques para predecir errores y una checklist viva que se alimenta de lo que encontramos.',
        reply: 'Exacto. Y que complementan a las técnicas formales, no las sustituyen.',
        effects: [{ kind: 'score', key: 'communication', add: 1 }, { kind: 'endMission' }],
      },
      {
        id: 'luck',
        text: 'Que encontrar bugs es cuestión de suerte.',
        reply: 'Mira en el debrief qué ataques encontraron cada bug: de suerte, poco.',
        effects: [{ kind: 'note', tone: 'neutral', text: 'Te quedaste con la suerte en lugar de con el método.' }, { kind: 'endMission' }],
      },
    ],
  },
]
