import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después (estilo examen CTFL, capítulos 5.1 y 5.2). */
export const m05Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'c2m5pre_3p',
      conceptId: 'estimation',
      question: 'Estimación de tres puntos con a = 6, m = 9 y b = 18 días. ¿Cuál es E? (K3)',
      options: ['9', '10', '11', '33'],
      correct: 1,
      explanation: '(6 + 36 + 18) ÷ 6 = 10.',
    },
    {
      id: 'c2m5pre_exit',
      conceptId: 'entry_exit',
      question: '¿Cuál de estos es un buen criterio de salida? (K2)',
      options: ['Cuando el equipo se sienta cómodo', 'Ningún defecto crítico abierto y todas las pruebas de riesgo alto ejecutadas', 'Cuando desarrollo diga', 'Cuando no queden bugs'],
      correct: 1,
      explanation: 'Es medible y está ligado al riesgo.',
    },
    {
      id: 'c2m5pre_risk',
      conceptId: 'risk_mgmt',
      question: '¿Cuál es un riesgo de proyecto? (K2)',
      options: ['El cálculo del IVA es incorrecto', 'El proveedor de una API se retrasa dos semanas', 'La aplicación es lenta con muchos usuarios', 'Hay un agujero de seguridad en el login'],
      correct: 1,
      explanation: 'Afecta a la gestión del proyecto, no a la calidad del producto.',
    },
    {
      id: 'c2m5pre_delphi',
      conceptId: 'estimation',
      question: 'En Wideband Delphi, ¿qué ocurre tras una ronda con mucha dispersión? (K2)',
      options: ['Se hace la media', 'Los extremos explican sus razones y se repite la estimación', 'Decide el más senior', 'Se descarta la técnica'],
      correct: 1,
      explanation: 'Se discute y se vuelve a estimar hasta converger.',
    },
    {
      id: 'c2m5pre_quad',
      conceptId: 'quadrants',
      question: '¿En qué cuadrante de testing están las pruebas de rendimiento? (K2)',
      options: ['Q1', 'Q2', 'Q3', 'Q4'],
      correct: 3,
      explanation: 'Q4: orientadas a tecnología y critican el producto.',
    },
    {
      id: 'c2m5pre_plan',
      conceptId: 'test_plan',
      question: '¿Qué NO suele formar parte de un plan de pruebas? (K1)',
      options: ['Alcance y objetivos', 'Registro de riesgos', 'El código fuente del producto', 'Criterios de entrada y salida'],
      correct: 2,
      explanation: 'El código no es parte del plan.',
    },
  ],
  post: [
    {
      id: 'c2m5post_3p',
      conceptId: 'estimation',
      question: 'Con a = 12, m = 18 y b = 36 persona-días, ¿cuál es la desviación estándar de la estimación de tres puntos? (K3)',
      options: ['2', '4', '6', '24'],
      correct: 1,
      explanation: '(36 − 12) ÷ 6 = 4.',
    },
    {
      id: 'c2m5post_ratio',
      conceptId: 'estimation',
      question: 'Históricamente, las pruebas son el 30 % del esfuerzo de desarrollo. Desarrollo estima 80 días. ¿Qué técnica y qué resultado? (K3)',
      options: ['Tres puntos · 24', 'Por ratios · 24', 'Delphi · 30', 'Extrapolación · 80'],
      correct: 1,
      explanation: '80 × 0,3 = 24, estimación por ratios.',
    },
    {
      id: 'c2m5post_prio',
      conceptId: 'prioritization',
      question: 'Un caso de riesgo alto depende de otro de riesgo medio. ¿Cuál se ejecuta antes? (K3)',
      options: ['El de riesgo alto', 'El de riesgo medio, por la dependencia', 'Da igual', 'Ninguno: se descarta la dependencia'],
      correct: 1,
      explanation: 'Las dependencias condicionan el orden.',
    },
    {
      id: 'c2m5post_quad',
      conceptId: 'quadrants',
      question: 'Las pruebas exploratorias y de usabilidad están en el cuadrante… (K2)',
      options: ['Q1', 'Q2', 'Q3', 'Q4'],
      correct: 2,
      explanation: 'Q3: orientadas a negocio y critican el producto.',
    },
    {
      id: 'c2m5post_risk',
      conceptId: 'risk_mgmt',
      question: '¿Qué afirmación sobre el nivel de riesgo es correcta? (K1)',
      options: ['Depende solo del impacto', 'Combina probabilidad e impacto', 'Lo fija el desarrollador', 'Solo existe en proyectos regulados'],
      correct: 1,
      explanation: 'Nivel de riesgo = probabilidad × impacto.',
    },
    {
      id: 'c2m5post_agile',
      conceptId: 'entry_exit',
      question: 'En ágil, ¿qué equivale habitualmente a los criterios de salida? (K1)',
      options: ['La definición de listo', 'La definición de hecho', 'El backlog', 'La retrospectiva'],
      correct: 1,
      explanation: 'La definición de hecho; la de listo equivale a los de entrada.',
    },
  ],
}
