import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 1 (testing estático y requisitos). */
export const m01Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm1pre_ambiguous',
      conceptId: 'requirement_defects',
      question: '«El descuento se aplica a clientes antiguos.» ¿Qué problema tiene este requisito?',
      options: ['Ninguno, está claro', 'Es ambiguo: no define qué es «antiguo»', 'Es contradictorio', 'Es demasiado técnico'],
      correct: 1,
      explanation: '«Antiguo» admite varias interpretaciones (¿un año?, ¿cinco?). Hay que preguntar el umbral.',
    },
    {
      id: 'm1pre_testable',
      conceptId: 'testable_criteria',
      question: '¿Cuál de estos criterios es verificable?',
      options: [
        'La app debe ser intuitiva',
        'La carga debe ser rápida',
        'El listado carga en menos de 2 segundos con 1.000 elementos',
        'El diseño debe gustar a los usuarios',
      ],
      correct: 2,
      explanation: 'Tiene un umbral medible y unas condiciones concretas: dos personas llegarían al mismo veredicto.',
    },
    {
      id: 'm1pre_shiftleft',
      conceptId: 'shift_left',
      question: '¿Cuándo es más barato encontrar un defecto?',
      options: ['En producción', 'En staging', 'En la revisión del requisito, antes de desarrollar', 'En la demo'],
      correct: 2,
      explanation: 'En el requisito cuesta una pregunta; después cuesta desarrollo, pruebas, corrección y re-test.',
    },
    {
      id: 'm1pre_incomplete',
      conceptId: 'requirement_defects',
      question: '«El usuario puede subir una foto de perfil.» ¿Qué falta casi seguro?',
      options: ['Nada', 'El color del botón', 'Formatos y tamaño máximo permitidos', 'El nombre del desarrollador'],
      correct: 2,
      explanation: 'Es un requisito incompleto: sin formatos y límites no se puede saber qué es un bug.',
    },
    {
      id: 'm1pre_dates',
      conceptId: 'boundary_values',
      question: 'Una reserva admite fechas «hasta 90 días vista». ¿Qué valores pruebas?',
      options: ['30 y 60 días', 'Hoy, 90 y 91 días', 'Solo 45 días', '1 y 2 días'],
      correct: 1,
      explanation: 'Los bordes: el primer día posible, el máximo y uno más allá del máximo.',
    },
    {
      id: 'm1pre_scope',
      conceptId: 'scope_change',
      question: 'A mitad de sprint la PO te pide que le digas al dev un cambio «rápido». ¿Qué haces?',
      options: [
        'Se lo digo al dev directamente',
        'Pido que se registre en el ticket y se valore su impacto con el equipo',
        'Lo ignoro',
        'Lo pruebo antes de que exista',
      ],
      correct: 1,
      explanation: 'Los cambios de alcance se registran y se valoran a la vista del equipo; los atajos acaban sin probar.',
    },
  ],
  post: [
    {
      id: 'm1post_ambiguous',
      conceptId: 'requirement_defects',
      question: '«Se aplican los mismos límites que en un pago normal.» ¿Qué tipo de defecto es?',
      options: ['Contradictorio', 'No verificable', 'Ambiguo: no dice qué límites ni cuándo se comprueban', 'No es un defecto'],
      correct: 2,
      explanation: '«Los mismos» obliga a interpretar cuáles y en qué momento se validan.',
    },
    {
      id: 'm1post_testable',
      conceptId: 'testable_criteria',
      question: '¿Cómo harías verificable «el registro debe ser fácil»?',
      options: [
        'Quitándolo de la historia',
        '«5 de 5 usuarios completan el registro sin ayuda en menos de 2 minutos»',
        '«El registro debe ser muy fácil»',
        'Pidiendo al dev que lo haga bonito',
      ],
      correct: 1,
      explanation: 'Un umbral objetivo permite decidir si pasa o falla.',
    },
    {
      id: 'm1post_shiftleft',
      conceptId: 'shift_left',
      question: 'Encontraste en la revisión que una regla de fechas era ambigua y la PO la aclaró antes de desarrollar. ¿Qué has conseguido?',
      options: ['Nada, igual habrá que probarlo', 'Retrasar al equipo', 'Evitar que ese bug llegue a escribirse', 'Hacer el trabajo del dev'],
      correct: 2,
      explanation: 'Es shift-left: el defecto se corrige en el requisito, donde cuesta una pregunta.',
    },
    {
      id: 'm1post_contradiction',
      conceptId: 'requirement_defects',
      question: 'La descripción dice «solo para empresas» y un ejemplo habla de «Ana compra para su casa». ¿Qué haces?',
      options: [
        'Sigo la descripción',
        'Sigo el ejemplo',
        'Lo marco como contradictorio y pregunto a la PO cuál es la regla',
        'Pruebo las dos y que gane la que funcione',
      ],
      correct: 2,
      explanation: 'Ante una contradicción no se elige a ojo: se pregunta y se deja escrita la respuesta.',
    },
    {
      id: 'm1post_dates',
      conceptId: 'boundary_values',
      question: 'Un pago mensual empieza el día 31. ¿Qué meses son clave para probarlo?',
      options: ['Enero y marzo', 'Los que tienen 31 días', 'Los de 30 días y febrero', 'Ninguno en especial'],
      correct: 2,
      explanation: 'Los meses sin día 31 son la partición que suele fallar (saltarse el pago o desplazarlo).',
    },
    {
      id: 'm1post_gwt',
      conceptId: 'given_when_then',
      question: '¿Qué aporta escribir un criterio como «Dado… Cuando… Entonces…»?',
      options: [
        'Nada, es burocracia',
        'Un ejemplo concreto que todo el equipo entiende igual y que se convierte en caso de prueba',
        'Que el dev no tenga que pensar',
        'Que la historia sea más larga',
      ],
      correct: 1,
      explanation: 'Los ejemplos eliminan interpretaciones y son casos de prueba listos para ejecutar.',
    },
  ],
}
