import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 2 (particiones, límites, combinaciones y oráculo). */
export const m02Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm2pre_base',
      conceptId: 'combinatorial',
      question: 'Un formulario tiene 4 campos con reglas. ¿Cuál es la estrategia más eficaz para empezar?',
      options: [
        'Probar todas las combinaciones posibles',
        'Fijar un caso válido y cambiar un solo campo cada vez, en sus particiones y bordes',
        'Probar valores al azar hasta que algo falle',
        'Probar solo el caso típico',
      ],
      correct: 1,
      explanation: 'Con una base válida, si un caso falla sabes exactamente qué campo lo causa.',
    },
    {
      id: 'm2pre_oracle',
      conceptId: 'test_oracle',
      question: 'El cálculo de una comisión te parece raro. ¿Qué necesitas para reportarlo?',
      options: ['Nada, basta con que me parezca raro', 'Un oráculo: la regla o un ejemplo validado con el resultado correcto', 'Que otro tester opine igual', 'Una captura de pantalla'],
      correct: 1,
      explanation: 'Sin oráculo no hay resultado esperado, y sin esperado no hay bug: hay una opinión.',
    },
    {
      id: 'm2pre_tier',
      conceptId: 'boundary_values',
      question: 'Una tarifa baja «a partir de 10.000 €». ¿Qué importes pruebas?',
      options: ['5.000 € y 20.000 €', '9.999,99 €, 10.000 € y 10.000,01 €', 'Solo 10.000 €', '1 € y 1.000.000 €'],
      correct: 1,
      explanation: 'Justo antes, justo en el umbral y justo después: ahí se esconde el «>» que debería ser «>=».',
    },
    {
      id: 'm2pre_combined',
      conceptId: 'boundary_values',
      question: 'Regla: «edad + años de carnet ≥ 25». ¿Qué caso es imprescindible?',
      options: ['Edad 40 y 20 años de carnet', 'Una combinación que sume exactamente 25', 'Solo la edad mínima', 'Solo los años de carnet mínimos'],
      correct: 1,
      explanation: 'El borde de una regla combinada es la combinación que cae justo en el límite.',
    },
    {
      id: 'm2pre_random',
      conceptId: 'random_vs_systematic',
      question: 'Un script ha probado 500 valores aleatorios sin fallos. ¿Qué concluyes?',
      options: [
        'Está bien probado',
        'Puede haber bugs en los bordes: lo aleatorio rara vez cae justo en ellos',
        'No hace falta diseñar casos',
        'El software no tiene bugs',
      ],
      correct: 1,
      explanation: 'Lo aleatorio complementa, pero no sustituye a las particiones y los valores límite.',
    },
    {
      id: 'm2pre_rounding',
      conceptId: 'calculation_testing',
      question: 'Una cuota sale 1 céntimo distinta del ejemplo validado. ¿Es un bug?',
      options: ['No, es solo redondeo', 'Sí, si la regla dice cómo redondear y el resultado no la cumple', 'Depende del humor del dev', 'Solo si son más de 10 céntimos'],
      correct: 1,
      explanation: 'En dinero no hay «casi»: un céntimo por miles de operaciones es un problema real y legal.',
    },
  ],
  post: [
    {
      id: 'm2post_base',
      conceptId: 'combinatorial',
      question: 'Una simulación falla con edad 17 e importe 999 a la vez. ¿Qué problema tiene ese caso?',
      options: ['Ninguno', 'Mezcla dos valores inválidos: no sabes cuál ha causado el resultado', 'Que 17 es muy joven', 'Que 999 no es redondo'],
      correct: 1,
      explanation: 'Cambia una variable cada vez sobre una base válida para poder aislar la causa.',
    },
    {
      id: 'm2post_oracle',
      conceptId: 'test_oracle',
      question: '¿Cuál de estos NO es un buen oráculo?',
      options: ['La política escrita', 'Una tabla de ejemplos validada por Riesgos', 'Lo que devuelve la propia app que estás probando', 'Una hoja de cálculo revisada'],
      correct: 2,
      explanation: 'La app bajo prueba no puede ser su propio oráculo: compararía el error consigo mismo.',
    },
    {
      id: 'm2post_tier',
      conceptId: 'boundary_values',
      question: 'Un descuento se aplica «desde 50 unidades». ¿Qué cantidades son clave?',
      options: ['10 y 100', '49, 50 y 51', 'Solo 50', '1 y 1.000'],
      correct: 1,
      explanation: 'Justo antes, en el umbral y justo después.',
    },
    {
      id: 'm2post_combined',
      conceptId: 'boundary_values',
      question: 'Regla: «edad + plazo en años ≤ 75». Con 68 años, ¿qué plazo prueba el borde exacto?',
      options: ['12 meses', '60 meses', '84 meses', '120 meses'],
      correct: 2,
      explanation: '68 + 7 años (84 meses) = 75: justo en el límite.',
    },
    {
      id: 'm2post_consistency',
      conceptId: 'calculation_testing',
      question: 'La cuota es 143,54 € a 48 meses y el total a devolver dice 6.889,84 €. ¿Qué ves?',
      options: ['Todo correcto', 'Una incoherencia: 143,54 × 48 = 6.889,92 €', 'Que el plazo es largo', 'Que faltan los intereses'],
      correct: 1,
      explanation: 'La coherencia interna (total = cuota × plazo) es un oráculo que siempre tienes a mano.',
    },
    {
      id: 'm2post_nfr',
      conceptId: 'non_functional',
      question: 'Staging va muy lento hoy. ¿Qué haces?',
      options: [
        'Abro un bug de rendimiento ya',
        'Lo ignoro, el rendimiento no es cosa de QA',
        'Aíslo la causa (entorno o sistema), lo anoto como riesgo y mido cuando el entorno esté estable',
        'Pido que lo desplieguen en producción para ver si va mejor',
      ],
      correct: 2,
      explanation: 'El rendimiento es calidad, pero se reporta con datos y con la causa aislada.',
    },
  ],
}
