import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 3 (transición de estados y tablas de decisión). */
export const m03Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm3pre_valid',
      conceptId: 'state_transition',
      question: 'Un pedido pasa por Recibido → Enviado → Entregado, y desde Recibido puede cancelarse. ¿Qué cobertura mínima esperas?',
      options: ['Solo el camino Recibido → Enviado → Entregado', 'Cada transición válida al menos una vez, comprobando el estado de llegada', 'Solo la cancelación', 'Ninguna: lo prueba el desarrollador'],
      correct: 1,
      explanation: 'Cada flecha del diagrama es al menos un caso, y se comprueba a qué estado se llega.',
    },
    {
      id: 'm3pre_invalid',
      conceptId: 'invalid_transitions',
      question: 'La interfaz no muestra el botón «Entregar» en un pedido cancelado. ¿Hace falta probar esa transición?',
      options: ['No, si el botón no se ve no se puede hacer', 'Sí: otro canal, la API o un doble clic pueden intentarla, y el sistema debe rechazarla', 'Solo si sobra tiempo', 'Solo en producción'],
      correct: 1,
      explanation: 'Ocultar un botón no es una regla de negocio. Las transiciones inválidas se prueban donde se validan.',
    },
    {
      id: 'm3pre_table',
      conceptId: 'decision_table',
      question: 'Una tabla de decisión tiene 3 condiciones y 5 reglas (columnas). ¿Cuántos casos mínimos?',
      options: ['1', '3', '5: uno por regla', '8 siempre'],
      correct: 2,
      explanation: 'Cada regla (columna) es al menos un caso. Con guiones (indiferente) puede convenir alguno más.',
    },
    {
      id: 'm3pre_dontcare',
      conceptId: 'decision_table',
      question: 'Regla R1: «Socio → clase gratis» (las demás condiciones, «–»). ¿Qué riesgo tiene probar solo un caso de R1?',
      options: ['Ninguno, el guion dice que da igual', 'Que otra regla se evalúe antes en el código y se «coma» a R1 en alguna combinación', 'Que el socio se enfade', 'Que la tabla esté mal dibujada'],
      correct: 1,
      explanation: 'El guion describe la intención; el código puede ordenar las reglas de otra forma. Prueba más de una combinación si hay riesgo.',
    },
    {
      id: 'm3pre_sequence',
      conceptId: 'switch_coverage',
      question: 'Se permiten devoluciones parciales de un cobro. ¿Qué caso es imprescindible?',
      options: ['Una devolución de 1 €', 'Varias devoluciones seguidas que sumen más que el cobro', 'Una devolución con el comercio cerrado', 'Ninguno, basta con una devolución'],
      correct: 1,
      explanation: 'Cada devolución suelta puede ser válida y la suma no: hay que probar secuencias que acumulan.',
    },
    {
      id: 'm3pre_incident',
      conceptId: 'incident_learning',
      question: 'Riesgos te cuenta una incidencia del sistema antiguo. ¿Qué haces con ella?',
      options: ['Nada, es otro sistema', 'La convierto en un caso de prueba del sistema nuevo', 'La reporto como bug del sistema nuevo', 'Se la paso al desarrollador'],
      correct: 1,
      explanation: 'Las incidencias pasadas son una de las mejores fuentes de casos: los bugs se migran con los requisitos.',
    },
  ],
  post: [
    {
      id: 'm3post_valid',
      conceptId: 'state_transition',
      question: 'Una suscripción: Prueba → Activa → Pausada → Activa, y Activa → Cancelada. ¿Qué demuestra que una transición funciona?',
      options: ['Que no aparece un error', 'Que el sistema llega al estado esperado (y conserva lo que debe)', 'Que el botón cambia de color', 'Que el log dice 200'],
      correct: 1,
      explanation: 'Sin comprobar el estado de llegada, un «200» puede esconder que la suscripción ha quedado en otro estado.',
    },
    {
      id: 'm3post_invalid',
      conceptId: 'invalid_transitions',
      question: 'Tienes poco tiempo. ¿Qué transiciones inválidas priorizas?',
      options: ['Las que nadie haría', 'Las que mueven dinero o datos y las que salen de estados finales', 'Las primeras de la tabla', 'Ninguna, solo las válidas'],
      correct: 1,
      explanation: 'Priorizar por riesgo también aplica a la tabla de estados: dinero, datos y estados que deberían ser finales.',
    },
    {
      id: 'm3post_result',
      conceptId: 'invalid_transitions',
      question: 'Intentas una transición inválida y el sistema responde «409». ¿Has terminado?',
      options: ['Sí', 'No: compruebo también que el objeto no ha cambiado (estado, importes, historial)', 'No: repito hasta que funcione', 'Sí, si el mensaje es claro'],
      correct: 1,
      explanation: 'Rechazar no basta: el rechazo no debe dejar efectos a medias.',
    },
    {
      id: 'm3post_boundary',
      conceptId: 'decision_table',
      question: 'Una condición de la tabla dice «hasta 30 días». ¿Qué valores pruebas en esa condición?',
      options: ['15 y 45', '30 y 31', 'Solo 30', '0 y 365'],
      correct: 1,
      explanation: 'Las condiciones de una tabla también tienen límites: justo dentro y justo fuera.',
    },
    {
      id: 'm3post_sequence',
      conceptId: 'switch_coverage',
      question: 'Tras ganar una disputa, el pago debe volver al estado anterior. ¿Qué cobertura detecta que vuelve siempre a «Liquidado»?',
      options: ['Probar «ganar disputa» una vez desde Liquidado', 'Secuencias: llegar a la disputa desde cada estado posible y ganarla', 'Probar todas las acciones una vez', 'Ninguna'],
      correct: 1,
      explanation: 'Es un bug de secuencia (1-switch): depende de por dónde se llegó al estado.',
    },
    {
      id: 'm3post_data',
      conceptId: 'test_data',
      question: 'Usas un generador para crear un cobro ya «En disputa». ¿Qué riesgo tiene?',
      options: ['Ninguno', 'Que el estado creado a mano no sea idéntico al real; conviene recorrer el camino real al menos una vez', 'Que el generador sea lento', 'Que el bug no cuente'],
      correct: 1,
      explanation: 'Los generadores aceleran la preparación, pero no sustituyen recorrer el camino real alguna vez.',
    },
  ],
}
