import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 4 (bug reports, aislamiento, severidad y prioridad). */
export const m04Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm4pre_title',
      conceptId: 'bug_report',
      question: '¿Cuál es el mejor título para un bug?',
      options: ['«El carrito no funciona»', '«El carrito se vacía al cambiar el idioma a francés (Android)»', '«URGENTE: carrito roto»', '«Bug en la app»'],
      correct: 1,
      explanation: 'Qué falla, dónde y en qué condición. Así se entiende sin abrirlo.',
    },
    {
      id: 'm4pre_sev_prio',
      conceptId: 'severity_priority',
      question: 'Hay una errata en el logo de la portada y mañana es el lanzamiento. ¿Severidad y prioridad?',
      options: ['Severidad crítica, prioridad alta', 'Severidad baja, prioridad alta', 'Severidad baja, prioridad baja', 'Severidad alta, prioridad baja'],
      correct: 1,
      explanation: 'No hace daño funcional (severidad baja), pero hay que arreglarlo ya por el lanzamiento (prioridad alta).',
    },
    {
      id: 'm4pre_isolate',
      conceptId: 'isolation',
      question: 'Un cliente dice: «En mi tablet, con la app en francés, al pagar con cupón, falla». ¿Qué haces primero?',
      options: ['Reportarlo tal cual', 'Cambiar una condición cada vez hasta saber cuál dispara el fallo', 'Pedir al cliente que reinstale la app', 'Probar en mi móvil y, si funciona, cerrarlo'],
      correct: 1,
      explanation: 'Aislar la condición convierte una queja en un bug reproducible.',
    },
    {
      id: 'm4pre_cant_repro',
      conceptId: 'environment',
      question: 'El desarrollador dice que no reproduce tu bug. ¿Qué haces?',
      options: ['Insistir en que a ti te pasa', 'Comparar entornos y datos para encontrar la diferencia y completar el report', 'Cerrarlo', 'Escalarlo al jefe'],
      correct: 1,
      explanation: 'Casi siempre falta una condición: dispositivo, idioma, cuenta, datos o secuencia.',
    },
    {
      id: 'm4pre_notbug',
      conceptId: 'not_a_bug',
      question: 'Un cliente ve dos cargos del súper, pero uno es una retención ya liberada. ¿Qué es?',
      options: ['Un bug crítico', 'Comportamiento esperado: se explica al cliente (y quizá se mejora el texto)', 'Un bug de severidad baja', 'Un problema del banco del cliente'],
      correct: 1,
      explanation: 'Si funciona como está definido no es un bug, aunque pueda merecer una mejora de usabilidad.',
    },
    {
      id: 'm4pre_inflate',
      conceptId: 'severity_priority',
      question: '¿Por qué no conviene marcar como «crítico» un bug menor para que lo arreglen antes?',
      options: ['Porque es más trabajo', 'Porque si todo es crítico nada lo es, y el equipo deja de fiarse de tu criterio', 'Porque el sistema no lo permite', 'Da igual'],
      correct: 1,
      explanation: 'La prioridad es la herramienta para «antes»; la severidad debe describir el daño.',
    },
  ],
  post: [
    {
      id: 'm4post_env',
      conceptId: 'environment',
      question: 'Un fallo solo ocurre con la cuenta de un tipo concreto. ¿Dónde lo indicas?',
      options: ['No hace falta', 'En el título y en el entorno/pasos del report', 'Solo en un comentario posterior', 'En la severidad'],
      correct: 1,
      explanation: 'La condición que dispara el fallo es la información más valiosa del report.',
    },
    {
      id: 'm4post_steps',
      conceptId: 'bug_report',
      question: '¿Qué pasos incluyes en un report?',
      options: ['Todo lo que hiciste durante la mañana', 'Los mínimos para reproducirlo, con los datos exactos', 'Solo el último clic', 'Ninguno: basta la captura'],
      correct: 1,
      explanation: 'Pasos mínimos y exactos: lo que no influye solo añade ruido.',
    },
    {
      id: 'm4post_rare',
      conceptId: 'severity_priority',
      question: 'Un error 500 en una función que usan 3 clientes y que tiene alternativa. ¿Qué es más probable?',
      options: ['Severidad baja, prioridad alta', 'Severidad alta, prioridad media o baja', 'Severidad crítica, prioridad urgente', 'No es un bug'],
      correct: 1,
      explanation: 'El daño es alto para quien lo sufre, pero el impacto global y la alternativa permiten planificarlo.',
    },
    {
      id: 'm4post_triage',
      conceptId: 'triage',
      question: 'En el triaje, ¿qué va primero?',
      options: ['El bug más antiguo', 'Lo que pone en riesgo dinero, seguridad o datos de clientes, y lo que bloquea un compromiso inminente', 'El que reportó el jefe', 'Los bugs fáciles'],
      correct: 1,
      explanation: 'La prioridad combina daño, alcance, alternativa y fechas de negocio.',
    },
    {
      id: 'm4post_returned',
      conceptId: 'bug_report',
      question: 'Te devuelven un report con «¿en qué dispositivo?». ¿Qué haces?',
      options: ['Abro uno nuevo', 'Lo completo con el dato y lo reenvío; y apunto incluir siempre el entorno', 'Lo dejo así', 'Respondo que es obvio'],
      correct: 1,
      explanation: 'Completar el mismo report mantiene el historial; la lección es que la próxima vez vaya completo.',
    },
    {
      id: 'm4post_evidence',
      conceptId: 'bug_report',
      question: '¿Qué evidencia adjuntas a un bug visual (una errata)?',
      options: ['Ninguna', 'Una captura de la pantalla con el entorno en el que aparece', 'Todos los logs del día', 'Un vídeo de 10 minutos'],
      correct: 1,
      explanation: 'Una captura concreta y el entorno: suficiente y sin ruido.',
    },
  ],
}
