import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 5 (riesgo, regresión, criterios de salida y go/no-go). */
export const m05Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm5pre_select',
      conceptId: 'risk_based',
      question: 'Tienes 4 horas y la regresión dura 7. ¿Qué haces?',
      options: ['Ejecutar en orden hasta que se acabe el tiempo', 'Priorizar por riesgo según lo que ha cambiado y decir qué queda sin probar', 'Pedir que se retrase la release siempre', 'Ejecutar solo lo más rápido'],
      correct: 1,
      explanation: 'El riesgo decide el orden, y lo no probado se comunica.',
    },
    {
      id: 'm5pre_unchanged',
      conceptId: 'regression_selection',
      question: 'Una zona no ha cambiado, pero usa una librería que se ha actualizado. ¿Riesgo?',
      options: ['Ninguno: no ha cambiado', 'Riesgo indirecto: puede romperse por la dependencia', 'Solo si lo dice el desarrollador', 'Solo en producción'],
      correct: 1,
      explanation: 'Las dependencias compartidas llevan el riesgo a zonas que nadie tocó.',
    },
    {
      id: 'm5pre_exit',
      conceptId: 'exit_criteria',
      question: '¿Qué son los criterios de salida?',
      options: ['La hora a la que se sale del trabajo', 'Condiciones acordadas para considerar que algo está listo para publicarse', 'El número de tests ejecutados', 'La firma del manager'],
      correct: 1,
      explanation: 'Se acuerdan antes de probar: así la decisión no depende del humor del día.',
    },
    {
      id: 'm5pre_flaky',
      conceptId: 'flaky_tests',
      question: 'Un test automático falla y al relanzarlo pasa; su historial muestra lo mismo otras veces. ¿Qué es?',
      options: ['Un bug crítico', 'Un test inestable (flaky): no bloquea, pero hay que estabilizarlo', 'Un fallo del servidor de CI', 'Nada importante'],
      correct: 1,
      explanation: 'Investigar el histórico separa un flaky de un fallo real.',
    },
    {
      id: 'm5pre_gonogo',
      conceptId: 'go_nogo',
      question: '¿Qué debe incluir una recomendación de GO/NO-GO de QA?',
      options: ['Solo «sí» o «no»', 'Qué se probó y qué no, bugs abiertos con su plan y riesgos residuales', 'El número de horas trabajadas', 'La opinión del desarrollador'],
      correct: 1,
      explanation: 'QA recomienda con datos; la decisión es del equipo.',
    },
    {
      id: 'm5pre_critical',
      conceptId: 'go_nogo',
      question: 'Hay un crítico abierto en una función que se puede desactivar con un flag. ¿Opción razonable?',
      options: ['NO-GO de toda la release siempre', 'GO con esa función desactivada y el crítico con plan de fix', 'GO sin decir nada', 'Esperar a que alguien decida'],
      correct: 1,
      explanation: 'Los flags permiten publicar lo que está bien y aislar el riesgo.',
    },
  ],
  post: [
    {
      id: 'm5post_notes',
      conceptId: 'risk_based',
      question: '¿Cuál es la mejor fuente para decidir qué regresión ejecutar?',
      options: ['El orden alfabético de los casos', 'Las notas de la versión (cambios, fixes y dependencias) junto con el impacto de cada zona', 'Los casos más cortos', 'Los que ejecutaste la última vez'],
      correct: 1,
      explanation: 'Lo que cambia sube la probabilidad; el impacto lo pone el negocio.',
    },
    {
      id: 'm5post_fix',
      conceptId: 'regression',
      question: 'Arreglan la comisión de las instantáneas a las 14:00. ¿Qué repites?',
      options: ['Nada, ya estaba probado', 'El caso que fallaba y los cercanos (p. ej. la transferencia ordinaria)', 'Toda la regresión completa', 'Solo la suite automática'],
      correct: 1,
      explanation: 'Re-test más regresión de lo que toca el mismo código.',
    },
    {
      id: 'm5post_time',
      conceptId: 'go_nogo',
      question: '«NO-GO: no me ha dado tiempo a probarlo todo.» ¿Qué le falta a este argumento?',
      options: ['Nada, es correcto', 'Un riesgo concreto: qué zona crítica queda sin probar o qué bug hay abierto', 'Más horas', 'La firma de QA'],
      correct: 1,
      explanation: 'Nunca da tiempo a todo: lo que importa es qué riesgo concreto queda.',
    },
    {
      id: 'm5post_early',
      conceptId: 'risk_based',
      question: '¿Por qué conviene ejecutar primero las zonas críticas?',
      options: ['Porque son más divertidas', 'Porque si hay un crítico, cuanto antes se encuentre, más tiempo hay para arreglarlo y verificarlo', 'Porque son más cortas', 'Da igual el orden'],
      correct: 1,
      explanation: 'Un crítico a las 15:30 deja la release sin margen.',
    },
    {
      id: 'm5post_hide',
      conceptId: 'go_nogo',
      question: 'A mediodía el manager pregunta «¿cómo vamos?» y tienes un crítico abierto. ¿Qué dices?',
      options: ['«Todo bien de momento», para no alarmar', 'El estado con datos, incluido el crítico y su plan', 'Nada hasta las 16:00', 'Que pregunte al desarrollador'],
      correct: 1,
      explanation: 'Las malas noticias, pronto: dan tiempo a decidir.',
    },
    {
      id: 'm5post_residual',
      conceptId: 'exit_criteria',
      question: 'Das GO con dos bugs medios abiertos. ¿Qué haces con ellos?',
      options: ['Nada', 'Los documento como riesgos conocidos con su plan y aviso a soporte', 'Los cierro', 'Los subo a críticos'],
      correct: 1,
      explanation: 'Un GO con riesgos conocidos documentados es una decisión; sin documentar, es una sorpresa.',
    },
  ],
}
