import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 6 (pirámide, niveles y tipos de prueba). */
export const m06Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm6pre_base',
      conceptId: 'test_pyramid',
      question: 'En una pirámide de pruebas sana, ¿de qué hay más?',
      options: ['Pruebas E2E por la interfaz', 'Pruebas unitarias', 'Pruebas manuales', 'Pruebas de rendimiento'],
      correct: 1,
      explanation: 'Las unitarias son rápidas, baratas y precisas: forman la base.',
    },
    {
      id: 'm6pre_calc',
      conceptId: 'test_levels',
      question: 'El cálculo de gastos de envío de una tienda online. ¿Dónde lo pruebas sobre todo?',
      options: ['E2E comprando de verdad', 'Unitarias del módulo que calcula', 'Manualmente cada release', 'No hace falta'],
      correct: 1,
      explanation: 'La lógica se prueba donde vive, con muchos casos y en milisegundos.',
    },
    {
      id: 'm6pre_auth',
      conceptId: 'test_levels',
      question: '«Un cliente no puede ver los pedidos de otro». ¿Dónde es imprescindible probarlo?',
      options: ['En la interfaz: si no hay botón, no se puede', 'En la API, llamándola con el usuario de otro', 'En una unitaria del cálculo', 'En producción'],
      correct: 1,
      explanation: 'La regla de seguridad vive en el servidor; la interfaz puede esconderla sin impedirla.',
    },
    {
      id: 'm6pre_ice',
      conceptId: 'test_pyramid',
      question: 'Una suite con 200 E2E y 20 unitarias tarda 50 minutos y falla una de cada cinco veces sin motivo. ¿Cómo se llama?',
      options: ['Pirámide', 'Cono de helado (pirámide invertida)', 'Suite completa', 'Integración continua'],
      correct: 1,
      explanation: 'Muchos E2E arriba y poca base: lenta, frágil y cara de mantener.',
    },
    {
      id: 'm6pre_types',
      conceptId: 'test_types',
      question: '¿Cuál de estos es un tipo de prueba no funcional?',
      options: ['Comprobar que el total del carrito es correcto', 'Medir que la búsqueda responde en menos de 1 s con 1.000 usuarios', 'Comprobar que un formulario rechaza un email inválido', 'Re-test de un fix'],
      correct: 1,
      explanation: 'El rendimiento es una característica no funcional y necesita su propia prueba.',
    },
    {
      id: 'm6pre_manual',
      conceptId: 'exploratory',
      question: '¿Qué conviene NO automatizar?',
      options: ['Validaciones de un formulario', 'Si una pantalla nueva se entiende y sus textos son claros', 'Un cálculo de intereses', 'El contrato de una API'],
      correct: 1,
      explanation: 'La claridad y la usabilidad necesitan criterio humano: exploratorias.',
    },
  ],
  post: [
    {
      id: 'm6post_mock',
      conceptId: 'contract_testing',
      question: 'La app y la API tienen sus unitarias en verde con mocks, pero juntas fallan. ¿Qué faltaba?',
      options: ['Más unitarias', 'Un test de contrato o de integración que compruebe el formato real que viaja', 'Más pruebas manuales', 'Nada, es mala suerte'],
      correct: 1,
      explanation: 'Los mocks reflejan lo que cada parte cree; el contrato comprueba lo que de verdad se envían.',
    },
    {
      id: 'm6post_time',
      conceptId: 'test_levels',
      question: 'Un recordatorio se envía a los 3 días. ¿Cómo lo pruebas?',
      options: ['E2E esperando 3 días', 'Unitaria (o API) con un reloj simulado', 'No se puede probar', 'Manualmente el jueves'],
      correct: 1,
      explanation: 'El tiempo se simula: ningún E2E puede esperar días.',
    },
    {
      id: 'm6post_perf',
      conceptId: 'test_types',
      question: 'El E2E de «crear reparto» con 3 amigos tarda 0,9 s. ¿Sabes si con 20 tardará menos de 2 s?',
      options: ['Sí, escala igual', 'No: hace falta una prueba de rendimiento con 20', 'Sí, si el E2E pasa', 'Da igual'],
      correct: 1,
      explanation: 'Las pruebas funcionales no responden preguntas de rendimiento.',
    },
    {
      id: 'm6post_e2e',
      conceptId: 'test_pyramid',
      question: '¿Cuántos E2E pondrías para una funcionalidad nueva típica?',
      options: ['Uno por cada regla', 'Pocos: los recorridos críticos de punta a punta', 'Ninguno', 'Tantos como unitarias'],
      correct: 1,
      explanation: 'Los E2E confirman que todo encaja; las reglas se cubren abajo.',
    },
    {
      id: 'm6post_ci',
      conceptId: 'test_pyramid',
      question: 'Tu suite tarda 45 minutos en cada cambio. ¿Qué pasa con el tiempo?',
      options: ['Nada', 'El equipo fusiona sin esperar el resultado y deja de fiarse de la suite', 'Mejora la calidad', 'Se encuentran más bugs'],
      correct: 1,
      explanation: 'Una suite lenta o frágil se acaba ignorando.',
    },
    {
      id: 'm6post_explore',
      conceptId: 'exploratory',
      question: 'Has automatizado todo lo repetitivo. ¿Qué haces con el tiempo que queda?',
      options: ['Más E2E', 'Exploración con objetivo: usabilidad, textos, accesibilidad y casos raros', 'Nada', 'Repetir la suite manualmente'],
      correct: 1,
      explanation: 'La automatización libera tiempo para lo que requiere criterio humano.',
    },
  ],
}
