import type { QuizQuestion } from '../../../engine/types'

/** Test antes y después de la misión 7 (incidentes, observabilidad, mitigación y postmortem). */
export const m07Quiz: { pre: QuizQuestion[]; post: QuizQuestion[] } = {
  pre: [
    {
      id: 'm7pre_first',
      conceptId: 'incident_response',
      question: 'Un fallo en producción afecta a clientes ahora mismo. ¿Qué es lo primero?',
      options: ['Encontrar la causa raíz exacta', 'Mitigar: reducir el daño cuanto antes', 'Escribir el postmortem', 'Buscar al responsable'],
      correct: 1,
      explanation: 'Primero se para el daño; la causa raíz se busca después (o en paralelo).',
    },
    {
      id: 'm7pre_narrow',
      conceptId: 'observability',
      question: 'Los pagos fallan al 4 %. ¿Cómo lo acotas con los datos?',
      options: ['Leyendo todos los logs uno a uno', 'Desglosando la tasa de errores por dimensiones y filtrando lo que destaca', 'Reiniciando servidores', 'Preguntando en el chat quién ha tocado algo'],
      correct: 1,
      explanation: 'Desglosar y filtrar, como al aislar una condición, lleva a la causa con pocas consultas.',
    },
    {
      id: 'm7pre_flag',
      conceptId: 'mitigation',
      question: '¿Qué ventaja tiene sacar una funcionalidad nueva detrás de un flag?',
      options: ['Ninguna', 'Si falla, se apaga en minutos sin hacer rollback de todo', 'Que no hace falta probarla', 'Que es más rápida'],
      correct: 1,
      explanation: 'El flag limita el daño y acelera la mitigación.',
    },
    {
      id: 'm7pre_comm',
      conceptId: 'incident_response',
      question: 'Atención al cliente pregunta qué decir y aún no sabes la causa. ¿Qué haces?',
      options: ['Nada hasta saberlo', 'Comunicar lo que sabes: qué falla, a quién afecta, qué hacer y cuándo habrá novedades', 'Decir que es culpa del banco del cliente', 'Prometer que se arregla en 10 minutos'],
      correct: 1,
      explanation: 'Comunicación honesta y frecuente, sin culpar ni prometer lo que no controlas.',
    },
    {
      id: 'm7pre_blameless',
      conceptId: 'postmortem',
      question: '¿Qué busca un postmortem sin culpables?',
      options: ['Quién cometió el error', 'Qué permitió que el error llegara a producción y qué cambiar en el sistema', 'Cuánto dinero se perdió', 'Cerrar el incidente rápido'],
      correct: 1,
      explanation: 'Se cambia el sistema (pruebas, alertas, procesos), no se busca a quién señalar.',
    },
    {
      id: 'm7pre_corr',
      conceptId: 'observability',
      question: 'Durante el incidente, la CPU de otro servicio está al 95 %, como cada día a esa hora. ¿Es la causa?',
      options: ['Seguro que sí', 'Probablemente no: no coincide en el tiempo con el inicio de los errores; hay que comprobar la correlación', 'Hay que reiniciarlo por si acaso', 'Da igual'],
      correct: 1,
      explanation: 'Correlación en el tiempo y en la dimensión afectada antes de perseguir una pista.',
    },
  ],
  post: [
    {
      id: 'm7post_blind',
      conceptId: 'mitigation',
      question: '¿Por qué no conviene desactivar flags a ciegas?',
      options: ['Porque está prohibido', 'Porque cuesta tiempo, puede quitar funcionalidades sanas y no arregla nada si no es la causa', 'Porque los flags no sirven', 'Da igual'],
      correct: 1,
      explanation: 'Primero se acota la funcionalidad afectada, después se apaga la correcta.',
    },
    {
      id: 'm7post_rollback',
      conceptId: 'mitigation',
      question: '¿Qué inconveniente tiene un rollback completo frente a desactivar un flag?',
      options: ['Ninguno', 'Es más lento y retira también lo bueno de la versión', 'No funciona nunca', 'Es más barato'],
      correct: 1,
      explanation: 'El rollback es la red de seguridad; el flag, el bisturí.',
    },
    {
      id: 'm7post_repro',
      conceptId: 'incident_response',
      question: 'Ya has mitigado. ¿Qué aporta QA ahora?',
      options: ['Nada, ya está', 'Reproducir el fallo en staging con la condición exacta, reportarlo y verificar el fix', 'Cerrar el incidente', 'Buscar culpables'],
      correct: 1,
      explanation: 'Reproducir y verificar convierten la mitigación en una solución.',
    },
    {
      id: 'm7post_cause',
      conceptId: 'postmortem',
      question: '«Diego subió código sin probar.» ¿Por qué no es una buena causa raíz?',
      options: ['Porque Diego es majo', 'Porque señala a una persona y no explica qué faltó en el sistema (pruebas, datos, alertas, despliegue)', 'Porque es falso', 'Porque es demasiado corta'],
      correct: 1,
      explanation: 'La causa raíz útil lleva a acciones que cambian el sistema.',
    },
    {
      id: 'm7post_actions',
      conceptId: 'shift_right',
      question: '¿Qué par de acciones encaja mejor con «shift-left + shift-right»?',
      options: ['Más reuniones y más documentación', 'Una prueba con datos reales que lo habría detectado y un despliegue gradual con alerta por versión', 'Prohibir los viernes', 'Más E2E'],
      correct: 1,
      explanation: 'Detectar antes y limitar el daño si aun así llega a producción.',
    },
    {
      id: 'm7post_data',
      conceptId: 'observability',
      question: 'Los errores solo aparecen en cuentas abiertas antes de 2024. ¿Qué faltó en las pruebas?',
      options: ['Nada', 'Datos de prueba representativos de producción (cuentas antiguas)', 'Más velocidad', 'Pruebas de usabilidad'],
      correct: 1,
      explanation: 'Si staging solo tiene datos «nuevos», los fallos de datos antiguos llegan a producción.',
    },
  ],
}
