"""add courses invitations and audit logs

Revision ID: a092a15e3706
Revises: 0b5e1a1c54f0
Create Date: 2026-04-27 10:11:44.082175

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a092a15e3706'
down_revision: Union[str, None] = '0b5e1a1c54f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

