import { jsPDF } from 'jspdf'
import { ASE_BRAND, loadAseLogoDataUrl, reportFooterLine } from './exportBranding'
import { drawBarChart, drawPieChart, type ChartDatum } from './pdfCharts'

export type AnalyticsPdfKpi = {
  label: string
  value: string | number
}

export type AnalyticsPdfBarChart = { title: string; data: ChartDatum[] }
export type AnalyticsPdfPieChart = { title: string; data: ChartDatum[] }

export type AnalyticsPdfOptions = {
  /** Report title, e.g. "Informe de analítica" / "Analytics report". */
  title: string
  /** Formatted date string to print under the title (already localized). */
  dateLabel: string
  kpis: AnalyticsPdfKpi[]
  /** File name to save as, e.g. `ase-analitica-2026-08-26.pdf`. */
  filename: string
  /** Name/email of the admin who triggered the export, shown in the footer. */
  generatedBy?: string
  lang?: 'es' | 'en'
  /** Bar chart sections rendered after the KPI table, one per chart block,
   * two blocks per page — turns the report into something presentable in a
   * meeting rather than just a data dump. */
  barCharts?: AnalyticsPdfBarChart[]
  /** Donut chart sections, laid out in the same block flow as `barCharts`. */
  pieCharts?: AnalyticsPdfPieChart[]
}

const PAGE_W = 595.28 // A4 pt
const PAGE_H = 841.89
const MARGIN_X = 48
const HEADER_H = 96
const FOOTER_TOP = PAGE_H - 54
const CONTENT_BOTTOM = PAGE_H - 66

/** Builds a branded, corporate-style one-page-plus PDF summary of the
 * admin analytics KPIs and triggers a browser download. Client-side only —
 * the caller passes in KPI values already available from existing
 * queries, no extra API calls are made here. Every page gets the same ASE
 * header band + logo and a confidentiality footer with page numbers, so
 * the output reads like an official company report rather than a raw data
 * dump. */
export async function downloadAnalyticsPdf({
  title,
  dateLabel,
  kpis,
  filename,
  generatedBy,
  lang = 'es',
  barCharts = [],
  pieCharts = [],
}: AnalyticsPdfOptions): Promise<void> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const { colors } = ASE_BRAND
  const logo = await loadAseLogoDataUrl()

  const drawHeader = () => {
    doc.setFillColor(colors.ink)
    doc.rect(0, 0, PAGE_W, HEADER_H, 'F')
    doc.setFillColor(colors.brand)
    doc.rect(0, HEADER_H, PAGE_W, 3, 'F')

    let textX = MARGIN_X
    if (logo) {
      try {
        doc.addImage(logo, 'PNG', MARGIN_X, 20, 52, 52)
        textX = MARGIN_X + 66
      } catch {
        // Malformed/unavailable image data — fall back to text-only header.
      }
    }

    doc.setTextColor(colors.brand)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text(ASE_BRAND.companyName.toUpperCase(), textX, 36)

    doc.setTextColor(colors.white)
    doc.setFontSize(17)
    doc.text(title, textX, 58)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(colors.mist)
    doc.text(dateLabel, textX, 76)
  }

  const drawFooter = (pageNum: number, pageCount: number) => {
    doc.setDrawColor(colors.line)
    doc.setLineWidth(0.75)
    doc.line(MARGIN_X, FOOTER_TOP, PAGE_W - MARGIN_X, FOOTER_TOP)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(colors.fog)
    doc.text(reportFooterLine(lang), MARGIN_X, FOOTER_TOP + 16)
    if (generatedBy) {
      doc.text(
        lang === 'en' ? `Generated by: ${generatedBy}` : `Generado por: ${generatedBy}`,
        MARGIN_X,
        FOOTER_TOP + 28,
      )
    }
    doc.text(
      lang === 'en' ? `Page ${pageNum} of ${pageCount}` : `Página ${pageNum} de ${pageCount}`,
      PAGE_W - MARGIN_X,
      FOOTER_TOP + 16,
      { align: 'right' },
    )
  }

  drawHeader()

  const labelX = MARGIN_X + 12
  const valueX = PAGE_W - MARGIN_X - 12
  const rowH = 24
  let y = HEADER_H + 44

  doc.setFillColor(colors.brandStrong)
  doc.rect(MARGIN_X, y - 17, PAGE_W - MARGIN_X * 2, 26, 'F')
  doc.setTextColor(colors.white)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9.5)
  doc.text(lang === 'en' ? 'INDICATOR' : 'INDICADOR', labelX, y)
  doc.text(lang === 'en' ? 'VALUE' : 'VALOR', valueX, y, { align: 'right' })
  y += rowH

  kpis.forEach((kpi, index) => {
    if (y > CONTENT_BOTTOM) {
      doc.addPage()
      drawHeader()
      y = HEADER_H + 44
    }

    if (index % 2 === 0) {
      doc.setFillColor(colors.chalk)
      doc.rect(MARGIN_X, y - 17, PAGE_W - MARGIN_X * 2, rowH, 'F')
    }

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(colors.graphite)
    doc.text(String(kpi.label), labelX, y)

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(colors.slate)
    doc.text(String(kpi.value), valueX, y, { align: 'right' })

    y += rowH
  })

  doc.setDrawColor(colors.line)
  doc.setLineWidth(0.5)
  doc.line(MARGIN_X, y - rowH + 8, PAGE_W - MARGIN_X, y - rowH + 8)

  // --- Chart sections: one visual block (bar or donut) per slot, two
  // slots stacked per page, each on its own fresh header page so the
  // report reads like presentation slides rather than a continuation of
  // the KPI table.
  const chartBlocks: Array<{ kind: 'bar' | 'pie'; title: string; data: ChartDatum[] }> = [
    ...barCharts.map((c) => ({ kind: 'bar' as const, ...c })),
    ...pieCharts.map((c) => ({ kind: 'pie' as const, ...c })),
  ].filter((block) => block.data.length > 0)

  const chartWidth = PAGE_W - MARGIN_X * 2
  const barHeight = 130
  const pieRadius = 62
  const blockGap = 40

  chartBlocks.forEach((block, index) => {
    let blockY: number
    if (index % 2 === 0) {
      doc.addPage()
      drawHeader()
      blockY = HEADER_H + 44
    } else {
      blockY = HEADER_H + 44 + barHeight + 70 + blockGap
    }

    if (block.kind === 'bar') {
      drawBarChart(doc, { x: MARGIN_X, y: blockY, width: chartWidth, height: barHeight, data: block.data, title: block.title })
    } else {
      drawPieChart(doc, { x: MARGIN_X, y: blockY, radius: pieRadius, data: block.data, title: block.title })
    }
  })

  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    drawFooter(page, pageCount)
  }

  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`)
}
